// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: l8events.proto

package l8events

import (
	l8api "github.com/saichler/l8types/go/types/l8api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Severity levels — universal across all projects.
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_INFO        Severity = 1
	Severity_SEVERITY_WARNING     Severity = 2
	Severity_SEVERITY_MINOR       Severity = 3
	Severity_SEVERITY_MAJOR       Severity = 4
	Severity_SEVERITY_CRITICAL    Severity = 5
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_INFO",
		2: "SEVERITY_WARNING",
		3: "SEVERITY_MINOR",
		4: "SEVERITY_MAJOR",
		5: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_INFO":        1,
		"SEVERITY_WARNING":     2,
		"SEVERITY_MINOR":       3,
		"SEVERITY_MAJOR":       4,
		"SEVERITY_CRITICAL":    5,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_l8events_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_l8events_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_l8events_proto_rawDescGZIP(), []int{0}
}

// Generic alarm lifecycle states.
type AlarmState int32

const (
	AlarmState_ALARM_STATE_UNSPECIFIED  AlarmState = 0
	AlarmState_ALARM_STATE_ACTIVE       AlarmState = 1
	AlarmState_ALARM_STATE_ACKNOWLEDGED AlarmState = 2
	AlarmState_ALARM_STATE_CLEARED      AlarmState = 3
	AlarmState_ALARM_STATE_SUPPRESSED   AlarmState = 4
)

// Enum value maps for AlarmState.
var (
	AlarmState_name = map[int32]string{
		0: "ALARM_STATE_UNSPECIFIED",
		1: "ALARM_STATE_ACTIVE",
		2: "ALARM_STATE_ACKNOWLEDGED",
		3: "ALARM_STATE_CLEARED",
		4: "ALARM_STATE_SUPPRESSED",
	}
	AlarmState_value = map[string]int32{
		"ALARM_STATE_UNSPECIFIED":  0,
		"ALARM_STATE_ACTIVE":       1,
		"ALARM_STATE_ACKNOWLEDGED": 2,
		"ALARM_STATE_CLEARED":      3,
		"ALARM_STATE_SUPPRESSED":   4,
	}
)

func (x AlarmState) Enum() *AlarmState {
	p := new(AlarmState)
	*p = x
	return p
}

func (x AlarmState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlarmState) Descriptor() protoreflect.EnumDescriptor {
	return file_l8events_proto_enumTypes[1].Descriptor()
}

func (AlarmState) Type() protoreflect.EnumType {
	return &file_l8events_proto_enumTypes[1]
}

func (x AlarmState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlarmState.Descriptor instead.
func (AlarmState) EnumDescriptor() ([]byte, []int) {
	return file_l8events_proto_rawDescGZIP(), []int{1}
}

// Generic event processing states.
type EventState int32

const (
	EventState_EVENT_STATE_UNSPECIFIED EventState = 0
	EventState_EVENT_STATE_NEW         EventState = 1
	EventState_EVENT_STATE_PROCESSED   EventState = 2
	EventState_EVENT_STATE_DISCARDED   EventState = 3
	EventState_EVENT_STATE_ARCHIVED    EventState = 4
)

// Enum value maps for EventState.
var (
	EventState_name = map[int32]string{
		0: "EVENT_STATE_UNSPECIFIED",
		1: "EVENT_STATE_NEW",
		2: "EVENT_STATE_PROCESSED",
		3: "EVENT_STATE_DISCARDED",
		4: "EVENT_STATE_ARCHIVED",
	}
	EventState_value = map[string]int32{
		"EVENT_STATE_UNSPECIFIED": 0,
		"EVENT_STATE_NEW":         1,
		"EVENT_STATE_PROCESSED":   2,
		"EVENT_STATE_DISCARDED":   3,
		"EVENT_STATE_ARCHIVED":    4,
	}
)

func (x EventState) Enum() *EventState {
	p := new(EventState)
	*p = x
	return p
}

func (x EventState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventState) Descriptor() protoreflect.EnumDescriptor {
	return file_l8events_proto_enumTypes[2].Descriptor()
}

func (EventState) Type() protoreflect.EnumType {
	return &file_l8events_proto_enumTypes[2]
}

func (x EventState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventState.Descriptor instead.
func (EventState) EnumDescriptor() ([]byte, []int) {
	return file_l8events_proto_rawDescGZIP(), []int{2}
}

// Event categories — covers audit, system, data center infrastructure, and extensible custom.
type EventCategory int32

const (
	EventCategory_EVENT_CATEGORY_UNSPECIFIED EventCategory = 0
	EventCategory_EVENT_CATEGORY_AUDIT       EventCategory = 1  // User action audit trail
	EventCategory_EVENT_CATEGORY_SYSTEM      EventCategory = 2  // System/infrastructure events
	EventCategory_EVENT_CATEGORY_MONITORING  EventCategory = 3  // Generic telemetry/monitoring
	EventCategory_EVENT_CATEGORY_SECURITY    EventCategory = 4  // Login, access, threat events
	EventCategory_EVENT_CATEGORY_INTEGRATION EventCategory = 5  // External system events
	EventCategory_EVENT_CATEGORY_CUSTOM      EventCategory = 6  // Consumer-defined category
	EventCategory_EVENT_CATEGORY_NETWORK     EventCategory = 7  // Device status, interfaces, routing (BGP/OSPF/MPLS/SR), hardware
	EventCategory_EVENT_CATEGORY_KUBERNETES  EventCategory = 8  // Pod, node, workload, namespace, network policy
	EventCategory_EVENT_CATEGORY_PERFORMANCE EventCategory = 9  // Threshold violations (CPU, memory, temperature, traffic)
	EventCategory_EVENT_CATEGORY_SYSLOG      EventCategory = 10 // Syslog messages from devices
	EventCategory_EVENT_CATEGORY_TRAP        EventCategory = 11 // SNMP traps from devices
	EventCategory_EVENT_CATEGORY_COMPUTE     EventCategory = 12 // Hypervisors, VMs, hosts
	EventCategory_EVENT_CATEGORY_STORAGE     EventCategory = 13 // Storage arrays, volumes, capacity
	EventCategory_EVENT_CATEGORY_POWER       EventCategory = 14 // PDUs, UPS, battery, power consumption
	EventCategory_EVENT_CATEGORY_GPU         EventCategory = 15 // GPU device status, utilization, temperature
	EventCategory_EVENT_CATEGORY_TOPOLOGY    EventCategory = 16 // Topology changes, link up/down, connectivity
	EventCategory_EVENT_CATEGORY_AUTOMATION  EventCategory = 17 // Workflow execution, policy compliance
)

// Enum value maps for EventCategory.
var (
	EventCategory_name = map[int32]string{
		0:  "EVENT_CATEGORY_UNSPECIFIED",
		1:  "EVENT_CATEGORY_AUDIT",
		2:  "EVENT_CATEGORY_SYSTEM",
		3:  "EVENT_CATEGORY_MONITORING",
		4:  "EVENT_CATEGORY_SECURITY",
		5:  "EVENT_CATEGORY_INTEGRATION",
		6:  "EVENT_CATEGORY_CUSTOM",
		7:  "EVENT_CATEGORY_NETWORK",
		8:  "EVENT_CATEGORY_KUBERNETES",
		9:  "EVENT_CATEGORY_PERFORMANCE",
		10: "EVENT_CATEGORY_SYSLOG",
		11: "EVENT_CATEGORY_TRAP",
		12: "EVENT_CATEGORY_COMPUTE",
		13: "EVENT_CATEGORY_STORAGE",
		14: "EVENT_CATEGORY_POWER",
		15: "EVENT_CATEGORY_GPU",
		16: "EVENT_CATEGORY_TOPOLOGY",
		17: "EVENT_CATEGORY_AUTOMATION",
	}
	EventCategory_value = map[string]int32{
		"EVENT_CATEGORY_UNSPECIFIED": 0,
		"EVENT_CATEGORY_AUDIT":       1,
		"EVENT_CATEGORY_SYSTEM":      2,
		"EVENT_CATEGORY_MONITORING":  3,
		"EVENT_CATEGORY_SECURITY":    4,
		"EVENT_CATEGORY_INTEGRATION": 5,
		"EVENT_CATEGORY_CUSTOM":      6,
		"EVENT_CATEGORY_NETWORK":     7,
		"EVENT_CATEGORY_KUBERNETES":  8,
		"EVENT_CATEGORY_PERFORMANCE": 9,
		"EVENT_CATEGORY_SYSLOG":      10,
		"EVENT_CATEGORY_TRAP":        11,
		"EVENT_CATEGORY_COMPUTE":     12,
		"EVENT_CATEGORY_STORAGE":     13,
		"EVENT_CATEGORY_POWER":       14,
		"EVENT_CATEGORY_GPU":         15,
		"EVENT_CATEGORY_TOPOLOGY":    16,
		"EVENT_CATEGORY_AUTOMATION":  17,
	}
)

func (x EventCategory) Enum() *EventCategory {
	p := new(EventCategory)
	*p = x
	return p
}

func (x EventCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_l8events_proto_enumTypes[3].Descriptor()
}

func (EventCategory) Type() protoreflect.EnumType {
	return &file_l8events_proto_enumTypes[3]
}

func (x EventCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventCategory.Descriptor instead.
func (EventCategory) EnumDescriptor() ([]byte, []int) {
	return file_l8events_proto_rawDescGZIP(), []int{3}
}

// Maintenance window status.
type MaintenanceStatus int32

const (
	MaintenanceStatus_MAINTENANCE_STATUS_UNSPECIFIED MaintenanceStatus = 0
	MaintenanceStatus_MAINTENANCE_STATUS_SCHEDULED   MaintenanceStatus = 1
	MaintenanceStatus_MAINTENANCE_STATUS_ACTIVE      MaintenanceStatus = 2
	MaintenanceStatus_MAINTENANCE_STATUS_COMPLETED   MaintenanceStatus = 3
	MaintenanceStatus_MAINTENANCE_STATUS_CANCELLED   MaintenanceStatus = 4
)

// Enum value maps for MaintenanceStatus.
var (
	MaintenanceStatus_name = map[int32]string{
		0: "MAINTENANCE_STATUS_UNSPECIFIED",
		1: "MAINTENANCE_STATUS_SCHEDULED",
		2: "MAINTENANCE_STATUS_ACTIVE",
		3: "MAINTENANCE_STATUS_COMPLETED",
		4: "MAINTENANCE_STATUS_CANCELLED",
	}
	MaintenanceStatus_value = map[string]int32{
		"MAINTENANCE_STATUS_UNSPECIFIED": 0,
		"MAINTENANCE_STATUS_SCHEDULED":   1,
		"MAINTENANCE_STATUS_ACTIVE":      2,
		"MAINTENANCE_STATUS_COMPLETED":   3,
		"MAINTENANCE_STATUS_CANCELLED":   4,
	}
)

func (x MaintenanceStatus) Enum() *MaintenanceStatus {
	p := new(MaintenanceStatus)
	*p = x
	return p
}

func (x MaintenanceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MaintenanceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_l8events_proto_enumTypes[4].Descriptor()
}

func (MaintenanceStatus) Type() protoreflect.EnumType {
	return &file_l8events_proto_enumTypes[4]
}

func (x MaintenanceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MaintenanceStatus.Descriptor instead.
func (MaintenanceStatus) EnumDescriptor() ([]byte, []int) {
	return file_l8events_proto_rawDescGZIP(), []int{4}
}

// Maintenance recurrence type.
type RecurrenceType int32

const (
	RecurrenceType_RECURRENCE_TYPE_UNSPECIFIED RecurrenceType = 0
	RecurrenceType_RECURRENCE_TYPE_NONE        RecurrenceType = 1
	RecurrenceType_RECURRENCE_TYPE_DAILY       RecurrenceType = 2
	RecurrenceType_RECURRENCE_TYPE_WEEKLY      RecurrenceType = 3
	RecurrenceType_RECURRENCE_TYPE_MONTHLY     RecurrenceType = 4
)

// Enum value maps for RecurrenceType.
var (
	RecurrenceType_name = map[int32]string{
		0: "RECURRENCE_TYPE_UNSPECIFIED",
		1: "RECURRENCE_TYPE_NONE",
		2: "RECURRENCE_TYPE_DAILY",
		3: "RECURRENCE_TYPE_WEEKLY",
		4: "RECURRENCE_TYPE_MONTHLY",
	}
	RecurrenceType_value = map[string]int32{
		"RECURRENCE_TYPE_UNSPECIFIED": 0,
		"RECURRENCE_TYPE_NONE":        1,
		"RECURRENCE_TYPE_DAILY":       2,
		"RECURRENCE_TYPE_WEEKLY":      3,
		"RECURRENCE_TYPE_MONTHLY":     4,
	}
)

func (x RecurrenceType) Enum() *RecurrenceType {
	p := new(RecurrenceType)
	*p = x
	return p
}

func (x RecurrenceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecurrenceType) Descriptor() protoreflect.EnumDescriptor {
	return file_l8events_proto_enumTypes[5].Descriptor()
}

func (RecurrenceType) Type() protoreflect.EnumType {
	return &file_l8events_proto_enumTypes[5]
}

func (x RecurrenceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecurrenceType.Descriptor instead.
func (RecurrenceType) EnumDescriptor() ([]byte, []int) {
	return file_l8events_proto_rawDescGZIP(), []int{5}
}

// A generic event occurrence.
// Consumers embed this in their own event types or use it directly.
// Immutable after creation — consumers should reject PUT on event services.
type EventRecord struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventId          string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Category         EventCategory          `protobuf:"varint,2,opt,name=category,proto3,enum=l8events.EventCategory" json:"category,omitempty"`
	EventType        string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	State            EventState             `protobuf:"varint,4,opt,name=state,proto3,enum=l8events.EventState" json:"state,omitempty"`
	Severity         Severity               `protobuf:"varint,5,opt,name=severity,proto3,enum=l8events.Severity" json:"severity,omitempty"`
	SourceId         string                 `protobuf:"bytes,6,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	SourceName       string                 `protobuf:"bytes,7,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	SourceType       string                 `protobuf:"bytes,8,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	Message          string                 `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	Attributes       map[string]string      `protobuf:"bytes,10,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OccurredAt       int64                  `protobuf:"varint,11,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	ReceivedAt       int64                  `protobuf:"varint,12,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	ProcessedAt      int64                  `protobuf:"varint,13,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	GeneratedAlarmId string                 `protobuf:"bytes,14,opt,name=generated_alarm_id,json=generatedAlarmId,proto3" json:"generated_alarm_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventRecord) Reset() {
	*x = EventRecord{}
	mi := &file_l8events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRecord) ProtoMessage() {}

func (x *EventRecord) ProtoReflect() protoreflect.Message {
	mi := &file_l8events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRecord.ProtoReflect.Descriptor instead.
func (*EventRecord) Descriptor() ([]byte, []int) {
	return file_l8events_proto_rawDescGZIP(), []int{0}
}

func (x *EventRecord) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventRecord) GetCategory() EventCategory {
	if x != nil {
		return x.Category
	}
	return EventCategory_EVENT_CATEGORY_UNSPECIFIED
}

func (x *EventRecord) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventRecord) GetState() EventState {
	if x != nil {
		return x.State
	}
	return EventState_EVENT_STATE_UNSPECIFIED
}

func (x *EventRecord) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *EventRecord) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *EventRecord) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *EventRecord) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *EventRecord) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EventRecord) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *EventRecord) GetOccurredAt() int64 {
	if x != nil {
		return x.OccurredAt
	}
	return 0
}

func (x *EventRecord) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

func (x *EventRecord) GetProcessedAt() int64 {
	if x != nil {
		return x.ProcessedAt
	}
	return 0
}

func (x *EventRecord) GetGeneratedAlarmId() string {
	if x != nil {
		return x.GeneratedAlarmId
	}
	return ""
}

// A note/comment attached to an alarm.
type AlarmNote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlarmNote) Reset() {
	*x = AlarmNote{}
	mi := &file_l8events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmNote) ProtoMessage() {}

func (x *AlarmNote) ProtoReflect() protoreflect.Message {
	mi := &file_l8events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmNote.ProtoReflect.Descriptor instead.
func (*AlarmNote) Descriptor() ([]byte, []int) {
	return file_l8events_proto_rawDescGZIP(), []int{1}
}

func (x *AlarmNote) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *AlarmNote) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *AlarmNote) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AlarmNote) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// A state transition record for alarm audit trail.
type AlarmStateChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromState     AlarmState             `protobuf:"varint,1,opt,name=from_state,json=fromState,proto3,enum=l8events.AlarmState" json:"from_state,omitempty"`
	ToState       AlarmState             `protobuf:"varint,2,opt,name=to_state,json=toState,proto3,enum=l8events.AlarmState" json:"to_state,omitempty"`
	ChangedBy     string                 `protobuf:"bytes,3,opt,name=changed_by,json=changedBy,proto3" json:"changed_by,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	ChangedAt     int64                  `protobuf:"varint,5,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlarmStateChange) Reset() {
	*x = AlarmStateChange{}
	mi := &file_l8events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmStateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmStateChange) ProtoMessage() {}

func (x *AlarmStateChange) ProtoReflect() protoreflect.Message {
	mi := &file_l8events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmStateChange.ProtoReflect.Descriptor instead.
func (*AlarmStateChange) Descriptor() ([]byte, []int) {
	return file_l8events_proto_rawDescGZIP(), []int{2}
}

func (x *AlarmStateChange) GetFromState() AlarmState {
	if x != nil {
		return x.FromState
	}
	return AlarmState_ALARM_STATE_UNSPECIFIED
}

func (x *AlarmStateChange) GetToState() AlarmState {
	if x != nil {
		return x.ToState
	}
	return AlarmState_ALARM_STATE_UNSPECIFIED
}

func (x *AlarmStateChange) GetChangedBy() string {
	if x != nil {
		return x.ChangedBy
	}
	return ""
}

func (x *AlarmStateChange) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AlarmStateChange) GetChangedAt() int64 {
	if x != nil {
		return x.ChangedAt
	}
	return 0
}

// A generic alarm instance — the core state machine.
// Consumers embed this in their own alarm types or extend it.
type AlarmRecord struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AlarmId          string                 `protobuf:"bytes,1,opt,name=alarm_id,json=alarmId,proto3" json:"alarm_id,omitempty"`
	DefinitionId     string                 `protobuf:"bytes,2,opt,name=definition_id,json=definitionId,proto3" json:"definition_id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	State            AlarmState             `protobuf:"varint,5,opt,name=state,proto3,enum=l8events.AlarmState" json:"state,omitempty"`
	Severity         Severity               `protobuf:"varint,6,opt,name=severity,proto3,enum=l8events.Severity" json:"severity,omitempty"`
	OriginalSeverity Severity               `protobuf:"varint,7,opt,name=original_severity,json=originalSeverity,proto3,enum=l8events.Severity" json:"original_severity,omitempty"`
	SourceId         string                 `protobuf:"bytes,8,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	SourceName       string                 `protobuf:"bytes,9,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	SourceType       string                 `protobuf:"bytes,10,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	FirstOccurrence  int64                  `protobuf:"varint,11,opt,name=first_occurrence,json=firstOccurrence,proto3" json:"first_occurrence,omitempty"`
	LastOccurrence   int64                  `protobuf:"varint,12,opt,name=last_occurrence,json=lastOccurrence,proto3" json:"last_occurrence,omitempty"`
	OccurrenceCount  int32                  `protobuf:"varint,13,opt,name=occurrence_count,json=occurrenceCount,proto3" json:"occurrence_count,omitempty"`
	DedupKey         string                 `protobuf:"bytes,14,opt,name=dedup_key,json=dedupKey,proto3" json:"dedup_key,omitempty"`
	EventId          string                 `protobuf:"bytes,15,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AcknowledgedBy   string                 `protobuf:"bytes,16,opt,name=acknowledged_by,json=acknowledgedBy,proto3" json:"acknowledged_by,omitempty"`
	AcknowledgedAt   int64                  `protobuf:"varint,17,opt,name=acknowledged_at,json=acknowledgedAt,proto3" json:"acknowledged_at,omitempty"`
	ClearedBy        string                 `protobuf:"bytes,18,opt,name=cleared_by,json=clearedBy,proto3" json:"cleared_by,omitempty"`
	ClearedAt        int64                  `protobuf:"varint,19,opt,name=cleared_at,json=clearedAt,proto3" json:"cleared_at,omitempty"`
	IsSuppressed     bool                   `protobuf:"varint,20,opt,name=is_suppressed,json=isSuppressed,proto3" json:"is_suppressed,omitempty"`
	SuppressedBy     string                 `protobuf:"bytes,21,opt,name=suppressed_by,json=suppressedBy,proto3" json:"suppressed_by,omitempty"`
	Attributes       map[string]string      `protobuf:"bytes,22,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Notes            []*AlarmNote           `protobuf:"bytes,23,rep,name=notes,proto3" json:"notes,omitempty"`
	StateHistory     []*AlarmStateChange    `protobuf:"bytes,24,rep,name=state_history,json=stateHistory,proto3" json:"state_history,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AlarmRecord) Reset() {
	*x = AlarmRecord{}
	mi := &file_l8events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmRecord) ProtoMessage() {}

func (x *AlarmRecord) ProtoReflect() protoreflect.Message {
	mi := &file_l8events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmRecord.ProtoReflect.Descriptor instead.
func (*AlarmRecord) Descriptor() ([]byte, []int) {
	return file_l8events_proto_rawDescGZIP(), []int{3}
}

func (x *AlarmRecord) GetAlarmId() string {
	if x != nil {
		return x.AlarmId
	}
	return ""
}

func (x *AlarmRecord) GetDefinitionId() string {
	if x != nil {
		return x.DefinitionId
	}
	return ""
}

func (x *AlarmRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlarmRecord) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AlarmRecord) GetState() AlarmState {
	if x != nil {
		return x.State
	}
	return AlarmState_ALARM_STATE_UNSPECIFIED
}

func (x *AlarmRecord) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *AlarmRecord) GetOriginalSeverity() Severity {
	if x != nil {
		return x.OriginalSeverity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *AlarmRecord) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *AlarmRecord) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *AlarmRecord) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *AlarmRecord) GetFirstOccurrence() int64 {
	if x != nil {
		return x.FirstOccurrence
	}
	return 0
}

func (x *AlarmRecord) GetLastOccurrence() int64 {
	if x != nil {
		return x.LastOccurrence
	}
	return 0
}

func (x *AlarmRecord) GetOccurrenceCount() int32 {
	if x != nil {
		return x.OccurrenceCount
	}
	return 0
}

func (x *AlarmRecord) GetDedupKey() string {
	if x != nil {
		return x.DedupKey
	}
	return ""
}

func (x *AlarmRecord) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AlarmRecord) GetAcknowledgedBy() string {
	if x != nil {
		return x.AcknowledgedBy
	}
	return ""
}

func (x *AlarmRecord) GetAcknowledgedAt() int64 {
	if x != nil {
		return x.AcknowledgedAt
	}
	return 0
}

func (x *AlarmRecord) GetClearedBy() string {
	if x != nil {
		return x.ClearedBy
	}
	return ""
}

func (x *AlarmRecord) GetClearedAt() int64 {
	if x != nil {
		return x.ClearedAt
	}
	return 0
}

func (x *AlarmRecord) GetIsSuppressed() bool {
	if x != nil {
		return x.IsSuppressed
	}
	return false
}

func (x *AlarmRecord) GetSuppressedBy() string {
	if x != nil {
		return x.SuppressedBy
	}
	return ""
}

func (x *AlarmRecord) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *AlarmRecord) GetNotes() []*AlarmNote {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *AlarmRecord) GetStateHistory() []*AlarmStateChange {
	if x != nil {
		return x.StateHistory
	}
	return nil
}

// Archive metadata — added when an alarm or event is archived.
type ArchiveInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArchivedAt    int64                  `protobuf:"varint,1,opt,name=archived_at,json=archivedAt,proto3" json:"archived_at,omitempty"`
	ArchivedBy    string                 `protobuf:"bytes,2,opt,name=archived_by,json=archivedBy,proto3" json:"archived_by,omitempty"`
	ArchiveReason string                 `protobuf:"bytes,3,opt,name=archive_reason,json=archiveReason,proto3" json:"archive_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveInfo) Reset() {
	*x = ArchiveInfo{}
	mi := &file_l8events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveInfo) ProtoMessage() {}

func (x *ArchiveInfo) ProtoReflect() protoreflect.Message {
	mi := &file_l8events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveInfo.ProtoReflect.Descriptor instead.
func (*ArchiveInfo) Descriptor() ([]byte, []int) {
	return file_l8events_proto_rawDescGZIP(), []int{4}
}

func (x *ArchiveInfo) GetArchivedAt() int64 {
	if x != nil {
		return x.ArchivedAt
	}
	return 0
}

func (x *ArchiveInfo) GetArchivedBy() string {
	if x != nil {
		return x.ArchivedBy
	}
	return ""
}

func (x *ArchiveInfo) GetArchiveReason() string {
	if x != nil {
		return x.ArchiveReason
	}
	return ""
}

// A maintenance window — period during which alarms/notifications are suppressed.
// Consumers store this in their own service; l8events provides the type and evaluator.
type MaintenanceWindow struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WindowId           string                 `protobuf:"bytes,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status             MaintenanceStatus      `protobuf:"varint,4,opt,name=status,proto3,enum=l8events.MaintenanceStatus" json:"status,omitempty"`
	StartTime          int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime            int64                  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	CreatedBy          string                 `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt          int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Recurrence         RecurrenceType         `protobuf:"varint,9,opt,name=recurrence,proto3,enum=l8events.RecurrenceType" json:"recurrence,omitempty"`
	RecurrenceInterval int32                  `protobuf:"varint,10,opt,name=recurrence_interval,json=recurrenceInterval,proto3" json:"recurrence_interval,omitempty"`
	ScopeIds           []string               `protobuf:"bytes,11,rep,name=scope_ids,json=scopeIds,proto3" json:"scope_ids,omitempty"`
	ScopeTypes         []string               `protobuf:"bytes,12,rep,name=scope_types,json=scopeTypes,proto3" json:"scope_types,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MaintenanceWindow) Reset() {
	*x = MaintenanceWindow{}
	mi := &file_l8events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceWindow) ProtoMessage() {}

func (x *MaintenanceWindow) ProtoReflect() protoreflect.Message {
	mi := &file_l8events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceWindow.ProtoReflect.Descriptor instead.
func (*MaintenanceWindow) Descriptor() ([]byte, []int) {
	return file_l8events_proto_rawDescGZIP(), []int{5}
}

func (x *MaintenanceWindow) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

func (x *MaintenanceWindow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MaintenanceWindow) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MaintenanceWindow) GetStatus() MaintenanceStatus {
	if x != nil {
		return x.Status
	}
	return MaintenanceStatus_MAINTENANCE_STATUS_UNSPECIFIED
}

func (x *MaintenanceWindow) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *MaintenanceWindow) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *MaintenanceWindow) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *MaintenanceWindow) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *MaintenanceWindow) GetRecurrence() RecurrenceType {
	if x != nil {
		return x.Recurrence
	}
	return RecurrenceType_RECURRENCE_TYPE_UNSPECIFIED
}

func (x *MaintenanceWindow) GetRecurrenceInterval() int32 {
	if x != nil {
		return x.RecurrenceInterval
	}
	return 0
}

func (x *MaintenanceWindow) GetScopeIds() []string {
	if x != nil {
		return x.ScopeIds
	}
	return nil
}

func (x *MaintenanceWindow) GetScopeTypes() []string {
	if x != nil {
		return x.ScopeTypes
	}
	return nil
}

type EventRecordList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*EventRecord         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata      *l8api.L8MetaData      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRecordList) Reset() {
	*x = EventRecordList{}
	mi := &file_l8events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRecordList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRecordList) ProtoMessage() {}

func (x *EventRecordList) ProtoReflect() protoreflect.Message {
	mi := &file_l8events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRecordList.ProtoReflect.Descriptor instead.
func (*EventRecordList) Descriptor() ([]byte, []int) {
	return file_l8events_proto_rawDescGZIP(), []int{6}
}

func (x *EventRecordList) GetList() []*EventRecord {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *EventRecordList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MaintenanceWindowList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*MaintenanceWindow   `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata      *l8api.L8MetaData      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaintenanceWindowList) Reset() {
	*x = MaintenanceWindowList{}
	mi := &file_l8events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceWindowList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceWindowList) ProtoMessage() {}

func (x *MaintenanceWindowList) ProtoReflect() protoreflect.Message {
	mi := &file_l8events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceWindowList.ProtoReflect.Descriptor instead.
func (*MaintenanceWindowList) Descriptor() ([]byte, []int) {
	return file_l8events_proto_rawDescGZIP(), []int{7}
}

func (x *MaintenanceWindowList) GetList() []*MaintenanceWindow {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *MaintenanceWindowList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_l8events_proto protoreflect.FileDescriptor

const file_l8events_proto_rawDesc = "" +
	"\n" +
	"\x0el8events.proto\x12\bl8events\x1a\tapi.proto\"\xea\x04\n" +
	"\vEventRecord\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x123\n" +
	"\bcategory\x18\x02 \x01(\x0e2\x17.l8events.EventCategoryR\bcategory\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12*\n" +
	"\x05state\x18\x04 \x01(\x0e2\x14.l8events.EventStateR\x05state\x12.\n" +
	"\bseverity\x18\x05 \x01(\x0e2\x12.l8events.SeverityR\bseverity\x12\x1b\n" +
	"\tsource_id\x18\x06 \x01(\tR\bsourceId\x12\x1f\n" +
	"\vsource_name\x18\a \x01(\tR\n" +
	"sourceName\x12\x1f\n" +
	"\vsource_type\x18\b \x01(\tR\n" +
	"sourceType\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage\x12E\n" +
	"\n" +
	"attributes\x18\n" +
	" \x03(\v2%.l8events.EventRecord.AttributesEntryR\n" +
	"attributes\x12\x1f\n" +
	"\voccurred_at\x18\v \x01(\x03R\n" +
	"occurredAt\x12\x1f\n" +
	"\vreceived_at\x18\f \x01(\x03R\n" +
	"receivedAt\x12!\n" +
	"\fprocessed_at\x18\r \x01(\x03R\vprocessedAt\x12,\n" +
	"\x12generated_alarm_id\x18\x0e \x01(\tR\x10generatedAlarmId\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\tAlarmNote\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"\xce\x01\n" +
	"\x10AlarmStateChange\x123\n" +
	"\n" +
	"from_state\x18\x01 \x01(\x0e2\x14.l8events.AlarmStateR\tfromState\x12/\n" +
	"\bto_state\x18\x02 \x01(\x0e2\x14.l8events.AlarmStateR\atoState\x12\x1d\n" +
	"\n" +
	"changed_by\x18\x03 \x01(\tR\tchangedBy\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"changed_at\x18\x05 \x01(\x03R\tchangedAt\"\x82\b\n" +
	"\vAlarmRecord\x12\x19\n" +
	"\balarm_id\x18\x01 \x01(\tR\aalarmId\x12#\n" +
	"\rdefinition_id\x18\x02 \x01(\tR\fdefinitionId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12*\n" +
	"\x05state\x18\x05 \x01(\x0e2\x14.l8events.AlarmStateR\x05state\x12.\n" +
	"\bseverity\x18\x06 \x01(\x0e2\x12.l8events.SeverityR\bseverity\x12?\n" +
	"\x11original_severity\x18\a \x01(\x0e2\x12.l8events.SeverityR\x10originalSeverity\x12\x1b\n" +
	"\tsource_id\x18\b \x01(\tR\bsourceId\x12\x1f\n" +
	"\vsource_name\x18\t \x01(\tR\n" +
	"sourceName\x12\x1f\n" +
	"\vsource_type\x18\n" +
	" \x01(\tR\n" +
	"sourceType\x12)\n" +
	"\x10first_occurrence\x18\v \x01(\x03R\x0ffirstOccurrence\x12'\n" +
	"\x0flast_occurrence\x18\f \x01(\x03R\x0elastOccurrence\x12)\n" +
	"\x10occurrence_count\x18\r \x01(\x05R\x0foccurrenceCount\x12\x1b\n" +
	"\tdedup_key\x18\x0e \x01(\tR\bdedupKey\x12\x19\n" +
	"\bevent_id\x18\x0f \x01(\tR\aeventId\x12'\n" +
	"\x0facknowledged_by\x18\x10 \x01(\tR\x0eacknowledgedBy\x12'\n" +
	"\x0facknowledged_at\x18\x11 \x01(\x03R\x0eacknowledgedAt\x12\x1d\n" +
	"\n" +
	"cleared_by\x18\x12 \x01(\tR\tclearedBy\x12\x1d\n" +
	"\n" +
	"cleared_at\x18\x13 \x01(\x03R\tclearedAt\x12#\n" +
	"\ris_suppressed\x18\x14 \x01(\bR\fisSuppressed\x12#\n" +
	"\rsuppressed_by\x18\x15 \x01(\tR\fsuppressedBy\x12E\n" +
	"\n" +
	"attributes\x18\x16 \x03(\v2%.l8events.AlarmRecord.AttributesEntryR\n" +
	"attributes\x12)\n" +
	"\x05notes\x18\x17 \x03(\v2\x13.l8events.AlarmNoteR\x05notes\x12?\n" +
	"\rstate_history\x18\x18 \x03(\v2\x1a.l8events.AlarmStateChangeR\fstateHistory\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"v\n" +
	"\vArchiveInfo\x12\x1f\n" +
	"\varchived_at\x18\x01 \x01(\x03R\n" +
	"archivedAt\x12\x1f\n" +
	"\varchived_by\x18\x02 \x01(\tR\n" +
	"archivedBy\x12%\n" +
	"\x0earchive_reason\x18\x03 \x01(\tR\rarchiveReason\"\xbc\x03\n" +
	"\x11MaintenanceWindow\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\tR\bwindowId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x123\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1b.l8events.MaintenanceStatusR\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x128\n" +
	"\n" +
	"recurrence\x18\t \x01(\x0e2\x18.l8events.RecurrenceTypeR\n" +
	"recurrence\x12/\n" +
	"\x13recurrence_interval\x18\n" +
	" \x01(\x05R\x12recurrenceInterval\x12\x1b\n" +
	"\tscope_ids\x18\v \x03(\tR\bscopeIds\x12\x1f\n" +
	"\vscope_types\x18\f \x03(\tR\n" +
	"scopeTypes\"k\n" +
	"\x0fEventRecordList\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.l8events.EventRecordR\x04list\x12-\n" +
	"\bmetadata\x18\x02 \x01(\v2\x11.l8api.L8MetaDataR\bmetadata\"w\n" +
	"\x15MaintenanceWindowList\x12/\n" +
	"\x04list\x18\x01 \x03(\v2\x1b.l8events.MaintenanceWindowR\x04list\x12-\n" +
	"\bmetadata\x18\x02 \x01(\v2\x11.l8api.L8MetaDataR\bmetadata*\x8c\x01\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x01\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x02\x12\x12\n" +
	"\x0eSEVERITY_MINOR\x10\x03\x12\x12\n" +
	"\x0eSEVERITY_MAJOR\x10\x04\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x05*\x94\x01\n" +
	"\n" +
	"AlarmState\x12\x1b\n" +
	"\x17ALARM_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ALARM_STATE_ACTIVE\x10\x01\x12\x1c\n" +
	"\x18ALARM_STATE_ACKNOWLEDGED\x10\x02\x12\x17\n" +
	"\x13ALARM_STATE_CLEARED\x10\x03\x12\x1a\n" +
	"\x16ALARM_STATE_SUPPRESSED\x10\x04*\x8e\x01\n" +
	"\n" +
	"EventState\x12\x1b\n" +
	"\x17EVENT_STATE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fEVENT_STATE_NEW\x10\x01\x12\x19\n" +
	"\x15EVENT_STATE_PROCESSED\x10\x02\x12\x19\n" +
	"\x15EVENT_STATE_DISCARDED\x10\x03\x12\x18\n" +
	"\x14EVENT_STATE_ARCHIVED\x10\x04*\x90\x04\n" +
	"\rEventCategory\x12\x1e\n" +
	"\x1aEVENT_CATEGORY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14EVENT_CATEGORY_AUDIT\x10\x01\x12\x19\n" +
	"\x15EVENT_CATEGORY_SYSTEM\x10\x02\x12\x1d\n" +
	"\x19EVENT_CATEGORY_MONITORING\x10\x03\x12\x1b\n" +
	"\x17EVENT_CATEGORY_SECURITY\x10\x04\x12\x1e\n" +
	"\x1aEVENT_CATEGORY_INTEGRATION\x10\x05\x12\x19\n" +
	"\x15EVENT_CATEGORY_CUSTOM\x10\x06\x12\x1a\n" +
	"\x16EVENT_CATEGORY_NETWORK\x10\a\x12\x1d\n" +
	"\x19EVENT_CATEGORY_KUBERNETES\x10\b\x12\x1e\n" +
	"\x1aEVENT_CATEGORY_PERFORMANCE\x10\t\x12\x19\n" +
	"\x15EVENT_CATEGORY_SYSLOG\x10\n" +
	"\x12\x17\n" +
	"\x13EVENT_CATEGORY_TRAP\x10\v\x12\x1a\n" +
	"\x16EVENT_CATEGORY_COMPUTE\x10\f\x12\x1a\n" +
	"\x16EVENT_CATEGORY_STORAGE\x10\r\x12\x18\n" +
	"\x14EVENT_CATEGORY_POWER\x10\x0e\x12\x16\n" +
	"\x12EVENT_CATEGORY_GPU\x10\x0f\x12\x1b\n" +
	"\x17EVENT_CATEGORY_TOPOLOGY\x10\x10\x12\x1d\n" +
	"\x19EVENT_CATEGORY_AUTOMATION\x10\x11*\xbc\x01\n" +
	"\x11MaintenanceStatus\x12\"\n" +
	"\x1eMAINTENANCE_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cMAINTENANCE_STATUS_SCHEDULED\x10\x01\x12\x1d\n" +
	"\x19MAINTENANCE_STATUS_ACTIVE\x10\x02\x12 \n" +
	"\x1cMAINTENANCE_STATUS_COMPLETED\x10\x03\x12 \n" +
	"\x1cMAINTENANCE_STATUS_CANCELLED\x10\x04*\x9f\x01\n" +
	"\x0eRecurrenceType\x12\x1f\n" +
	"\x1bRECURRENCE_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14RECURRENCE_TYPE_NONE\x10\x01\x12\x19\n" +
	"\x15RECURRENCE_TYPE_DAILY\x10\x02\x12\x1a\n" +
	"\x16RECURRENCE_TYPE_WEEKLY\x10\x03\x12\x1b\n" +
	"\x17RECURRENCE_TYPE_MONTHLY\x10\x04B\x12Z\x10./types/l8eventsb\x06proto3"

var (
	file_l8events_proto_rawDescOnce sync.Once
	file_l8events_proto_rawDescData []byte
)

func file_l8events_proto_rawDescGZIP() []byte {
	file_l8events_proto_rawDescOnce.Do(func() {
		file_l8events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_l8events_proto_rawDesc), len(file_l8events_proto_rawDesc)))
	})
	return file_l8events_proto_rawDescData
}

var file_l8events_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_l8events_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_l8events_proto_goTypes = []any{
	(Severity)(0),                 // 0: l8events.Severity
	(AlarmState)(0),               // 1: l8events.AlarmState
	(EventState)(0),               // 2: l8events.EventState
	(EventCategory)(0),            // 3: l8events.EventCategory
	(MaintenanceStatus)(0),        // 4: l8events.MaintenanceStatus
	(RecurrenceType)(0),           // 5: l8events.RecurrenceType
	(*EventRecord)(nil),           // 6: l8events.EventRecord
	(*AlarmNote)(nil),             // 7: l8events.AlarmNote
	(*AlarmStateChange)(nil),      // 8: l8events.AlarmStateChange
	(*AlarmRecord)(nil),           // 9: l8events.AlarmRecord
	(*ArchiveInfo)(nil),           // 10: l8events.ArchiveInfo
	(*MaintenanceWindow)(nil),     // 11: l8events.MaintenanceWindow
	(*EventRecordList)(nil),       // 12: l8events.EventRecordList
	(*MaintenanceWindowList)(nil), // 13: l8events.MaintenanceWindowList
	nil,                           // 14: l8events.EventRecord.AttributesEntry
	nil,                           // 15: l8events.AlarmRecord.AttributesEntry
	(*l8api.L8MetaData)(nil),      // 16: l8api.L8MetaData
}
var file_l8events_proto_depIdxs = []int32{
	3,  // 0: l8events.EventRecord.category:type_name -> l8events.EventCategory
	2,  // 1: l8events.EventRecord.state:type_name -> l8events.EventState
	0,  // 2: l8events.EventRecord.severity:type_name -> l8events.Severity
	14, // 3: l8events.EventRecord.attributes:type_name -> l8events.EventRecord.AttributesEntry
	1,  // 4: l8events.AlarmStateChange.from_state:type_name -> l8events.AlarmState
	1,  // 5: l8events.AlarmStateChange.to_state:type_name -> l8events.AlarmState
	1,  // 6: l8events.AlarmRecord.state:type_name -> l8events.AlarmState
	0,  // 7: l8events.AlarmRecord.severity:type_name -> l8events.Severity
	0,  // 8: l8events.AlarmRecord.original_severity:type_name -> l8events.Severity
	15, // 9: l8events.AlarmRecord.attributes:type_name -> l8events.AlarmRecord.AttributesEntry
	7,  // 10: l8events.AlarmRecord.notes:type_name -> l8events.AlarmNote
	8,  // 11: l8events.AlarmRecord.state_history:type_name -> l8events.AlarmStateChange
	4,  // 12: l8events.MaintenanceWindow.status:type_name -> l8events.MaintenanceStatus
	5,  // 13: l8events.MaintenanceWindow.recurrence:type_name -> l8events.RecurrenceType
	6,  // 14: l8events.EventRecordList.list:type_name -> l8events.EventRecord
	16, // 15: l8events.EventRecordList.metadata:type_name -> l8api.L8MetaData
	11, // 16: l8events.MaintenanceWindowList.list:type_name -> l8events.MaintenanceWindow
	16, // 17: l8events.MaintenanceWindowList.metadata:type_name -> l8api.L8MetaData
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_l8events_proto_init() }
func file_l8events_proto_init() {
	if File_l8events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_l8events_proto_rawDesc), len(file_l8events_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_l8events_proto_goTypes,
		DependencyIndexes: file_l8events_proto_depIdxs,
		EnumInfos:         file_l8events_proto_enumTypes,
		MessageInfos:      file_l8events_proto_msgTypes,
	}.Build()
	File_l8events_proto = out.File
	file_l8events_proto_goTypes = nil
	file_l8events_proto_depIdxs = nil
}
