// © 2025 Sharon Aicler (saichler@gmail.com)
//
// Layer 8 Ecosystem is licensed under the Apache License, Version 2.0.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// api.proto defines the core API types for the Layer 8 distributed system.
// This includes query DSL for data filtering, authentication and authorization,
// two-factor authentication (TFA), captcha support, and credential management.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: api.proto

package l8api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type L8PeriodType int32

const (
	L8PeriodType_invalid_period_type L8PeriodType = 0
	L8PeriodType_Yearly              L8PeriodType = 1
	L8PeriodType_Quarterly           L8PeriodType = 2
	L8PeriodType_Monthly             L8PeriodType = 3
)

// Enum value maps for L8PeriodType.
var (
	L8PeriodType_name = map[int32]string{
		0: "invalid_period_type",
		1: "Yearly",
		2: "Quarterly",
		3: "Monthly",
	}
	L8PeriodType_value = map[string]int32{
		"invalid_period_type": 0,
		"Yearly":              1,
		"Quarterly":           2,
		"Monthly":             3,
	}
)

func (x L8PeriodType) Enum() *L8PeriodType {
	p := new(L8PeriodType)
	*p = x
	return p
}

func (x L8PeriodType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L8PeriodType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[0].Descriptor()
}

func (L8PeriodType) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[0]
}

func (x L8PeriodType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use L8PeriodType.Descriptor instead.
func (L8PeriodType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

type L8PeriodValue int32

const (
	L8PeriodValue_invalid_period_value L8PeriodValue = 0
	L8PeriodValue_January              L8PeriodValue = 1
	L8PeriodValue_February             L8PeriodValue = 2
	L8PeriodValue_March                L8PeriodValue = 3
	L8PeriodValue_April                L8PeriodValue = 4
	L8PeriodValue_May                  L8PeriodValue = 5
	L8PeriodValue_June                 L8PeriodValue = 6
	L8PeriodValue_July                 L8PeriodValue = 7
	L8PeriodValue_August               L8PeriodValue = 8
	L8PeriodValue_September            L8PeriodValue = 9
	L8PeriodValue_October              L8PeriodValue = 10
	L8PeriodValue_November             L8PeriodValue = 11
	L8PeriodValue_December             L8PeriodValue = 12
	L8PeriodValue_Q1                   L8PeriodValue = 13
	L8PeriodValue_Q2                   L8PeriodValue = 14
	L8PeriodValue_Q3                   L8PeriodValue = 15
	L8PeriodValue_Q4                   L8PeriodValue = 16
)

// Enum value maps for L8PeriodValue.
var (
	L8PeriodValue_name = map[int32]string{
		0:  "invalid_period_value",
		1:  "January",
		2:  "February",
		3:  "March",
		4:  "April",
		5:  "May",
		6:  "June",
		7:  "July",
		8:  "August",
		9:  "September",
		10: "October",
		11: "November",
		12: "December",
		13: "Q1",
		14: "Q2",
		15: "Q3",
		16: "Q4",
	}
	L8PeriodValue_value = map[string]int32{
		"invalid_period_value": 0,
		"January":              1,
		"February":             2,
		"March":                3,
		"April":                4,
		"May":                  5,
		"June":                 6,
		"July":                 7,
		"August":               8,
		"September":            9,
		"October":              10,
		"November":             11,
		"December":             12,
		"Q1":                   13,
		"Q2":                   14,
		"Q3":                   15,
		"Q4":                   16,
	}
)

func (x L8PeriodValue) Enum() *L8PeriodValue {
	p := new(L8PeriodValue)
	*p = x
	return p
}

func (x L8PeriodValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L8PeriodValue) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[1].Descriptor()
}

func (L8PeriodValue) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[1]
}

func (x L8PeriodValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use L8PeriodValue.Descriptor instead.
func (L8PeriodValue) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

// L8Query represents a query request for filtering and retrieving data elements.
// It supports expression-based criteria, sorting, pagination, and map-reduce operations.
type L8Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Free-text search string for full-text queries
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// The root type name to query against
	RootType string `protobuf:"bytes,2,opt,name=rootType,proto3" json:"rootType,omitempty"`
	// List of property names to include in the result (projection)
	Properties []string `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty"`
	// The filter criteria expression tree
	Criteria *L8Expression `protobuf:"bytes,4,opt,name=criteria,proto3" json:"criteria,omitempty"`
	// Property name to sort results by
	SortBy string `protobuf:"bytes,5,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	// If true, sort in descending order; otherwise ascending
	Descending bool `protobuf:"varint,6,opt,name=descending,proto3" json:"descending,omitempty"`
	// Maximum number of results to return per page
	Limit int32 `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	// Page number for pagination (zero-based)
	Page int32 `protobuf:"varint,8,opt,name=page,proto3" json:"page,omitempty"`
	// If true, perform case-sensitive matching
	MatchCase bool `protobuf:"varint,9,opt,name=match_case,json=matchCase,proto3" json:"match_case,omitempty"`
	// Schema name to filter by (optional)
	Schema string `protobuf:"bytes,10,opt,name=schema,proto3" json:"schema,omitempty"`
	// If true, execute as a distributed map-reduce operation
	MapReduce bool `protobuf:"varint,11,opt,name=map_reduce,json=mapReduce,proto3" json:"map_reduce,omitempty"`
}

func (x *L8Query) Reset() {
	*x = L8Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8Query) ProtoMessage() {}

func (x *L8Query) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8Query.ProtoReflect.Descriptor instead.
func (*L8Query) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *L8Query) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *L8Query) GetRootType() string {
	if x != nil {
		return x.RootType
	}
	return ""
}

func (x *L8Query) GetProperties() []string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *L8Query) GetCriteria() *L8Expression {
	if x != nil {
		return x.Criteria
	}
	return nil
}

func (x *L8Query) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *L8Query) GetDescending() bool {
	if x != nil {
		return x.Descending
	}
	return false
}

func (x *L8Query) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *L8Query) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *L8Query) GetMatchCase() bool {
	if x != nil {
		return x.MatchCase
	}
	return false
}

func (x *L8Query) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *L8Query) GetMapReduce() bool {
	if x != nil {
		return x.MapReduce
	}
	return false
}

// L8Expression represents a node in the query criteria expression tree.
// Expressions can be chained using AND/OR logic and nested with child expressions.
type L8Expression struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The condition at this expression node
	Condition *L8Condition `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	// Logical operator to chain with next expression ("AND" or "OR")
	AndOr string `protobuf:"bytes,2,opt,name=and_or,json=andOr,proto3" json:"and_or,omitempty"`
	// Next expression in the chain (sibling)
	Next *L8Expression `protobuf:"bytes,3,opt,name=next,proto3" json:"next,omitempty"`
	// Nested child expression (for grouping)
	Child *L8Expression `protobuf:"bytes,4,opt,name=child,proto3" json:"child,omitempty"`
}

func (x *L8Expression) Reset() {
	*x = L8Expression{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8Expression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8Expression) ProtoMessage() {}

func (x *L8Expression) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8Expression.ProtoReflect.Descriptor instead.
func (*L8Expression) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *L8Expression) GetCondition() *L8Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *L8Expression) GetAndOr() string {
	if x != nil {
		return x.AndOr
	}
	return ""
}

func (x *L8Expression) GetNext() *L8Expression {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *L8Expression) GetChild() *L8Expression {
	if x != nil {
		return x.Child
	}
	return nil
}

// L8Condition represents a condition within an expression.
// Conditions contain comparators and can be chained together.
type L8Condition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The comparator defining the comparison operation
	Comparator *L8Comparator `protobuf:"bytes,1,opt,name=comparator,proto3" json:"comparator,omitempty"`
	// Operator to chain with next condition
	Oper string `protobuf:"bytes,2,opt,name=oper,proto3" json:"oper,omitempty"`
	// Next condition in the chain
	Next *L8Condition `protobuf:"bytes,3,opt,name=next,proto3" json:"next,omitempty"`
}

func (x *L8Condition) Reset() {
	*x = L8Condition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8Condition) ProtoMessage() {}

func (x *L8Condition) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8Condition.ProtoReflect.Descriptor instead.
func (*L8Condition) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *L8Condition) GetComparator() *L8Comparator {
	if x != nil {
		return x.Comparator
	}
	return nil
}

func (x *L8Condition) GetOper() string {
	if x != nil {
		return x.Oper
	}
	return ""
}

func (x *L8Condition) GetNext() *L8Condition {
	if x != nil {
		return x.Next
	}
	return nil
}

// L8Comparator defines a single comparison operation.
// Compares a left operand against a right operand using an operator.
type L8Comparator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Left operand (typically a property name)
	Left string `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	// Comparison operator (e.g., "=", "!=", ">", "<", ">=", "<=", "LIKE", "IN")
	Oper string `protobuf:"bytes,2,opt,name=oper,proto3" json:"oper,omitempty"`
	// Right operand (the value to compare against)
	Right string `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
}

func (x *L8Comparator) Reset() {
	*x = L8Comparator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8Comparator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8Comparator) ProtoMessage() {}

func (x *L8Comparator) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8Comparator.ProtoReflect.Descriptor instead.
func (*L8Comparator) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *L8Comparator) GetLeft() string {
	if x != nil {
		return x.Left
	}
	return ""
}

func (x *L8Comparator) GetOper() string {
	if x != nil {
		return x.Oper
	}
	return ""
}

func (x *L8Comparator) GetRight() string {
	if x != nil {
		return x.Right
	}
	return ""
}

// AuthUser contains user credentials for authentication requests.
type AuthUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Username or email for authentication
	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// Password (should be transmitted over secure channel)
	Pass string `protobuf:"bytes,2,opt,name=pass,proto3" json:"pass,omitempty"`
	// Captcha response token for bot protection
	Captcha string `protobuf:"bytes,3,opt,name=captcha,proto3" json:"captcha,omitempty"`
}

func (x *AuthUser) Reset() {
	*x = AuthUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUser) ProtoMessage() {}

func (x *AuthUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUser.ProtoReflect.Descriptor instead.
func (*AuthUser) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *AuthUser) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *AuthUser) GetPass() string {
	if x != nil {
		return x.Pass
	}
	return ""
}

func (x *AuthUser) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

// AuthToken is the response to an authentication request.
// Contains the session token or error information.
type AuthToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The authentication token if successful
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Error message if authentication failed
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// If true, user needs to set up two-factor authentication
	SetupTfa bool `protobuf:"varint,3,opt,name=setup_tfa,json=setupTfa,proto3" json:"setup_tfa,omitempty"`
	// If true, user needs to provide TFA code to complete login
	NeedTfa bool `protobuf:"varint,4,opt,name=need_tfa,json=needTfa,proto3" json:"need_tfa,omitempty"`
}

func (x *AuthToken) Reset() {
	*x = AuthToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthToken) ProtoMessage() {}

func (x *AuthToken) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthToken.ProtoReflect.Descriptor instead.
func (*AuthToken) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *AuthToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthToken) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AuthToken) GetSetupTfa() bool {
	if x != nil {
		return x.SetupTfa
	}
	return false
}

func (x *AuthToken) GetNeedTfa() bool {
	if x != nil {
		return x.NeedTfa
	}
	return false
}

// L8MetaData provides metadata and statistics about query results.
// Used for aggregation and analysis of data distribution.
type L8MetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Count statistics for primary keys
	KeyCount *L8Count `protobuf:"bytes,1,opt,name=key_count,json=keyCount,proto3" json:"key_count,omitempty"`
	// Count statistics per value, keyed by property name
	ValueCount map[string]*L8Count `protobuf:"bytes,2,rep,name=value_count,json=valueCount,proto3" json:"value_count,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *L8MetaData) Reset() {
	*x = L8MetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8MetaData) ProtoMessage() {}

func (x *L8MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8MetaData.ProtoReflect.Descriptor instead.
func (*L8MetaData) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *L8MetaData) GetKeyCount() *L8Count {
	if x != nil {
		return x.KeyCount
	}
	return nil
}

func (x *L8MetaData) GetValueCount() map[string]*L8Count {
	if x != nil {
		return x.ValueCount
	}
	return nil
}

// L8Count holds count statistics as a map of value to count.
type L8Count struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Map of value string to occurrence count
	Counts map[string]int32 `protobuf:"bytes,1,rep,name=counts,proto3" json:"counts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *L8Count) Reset() {
	*x = L8Count{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8Count) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8Count) ProtoMessage() {}

func (x *L8Count) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8Count.ProtoReflect.Descriptor instead.
func (*L8Count) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *L8Count) GetCounts() map[string]int32 {
	if x != nil {
		return x.Counts
	}
	return nil
}

// L8TypeList contains a list of type names.
type L8TypeList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of type name strings
	List []string `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *L8TypeList) Reset() {
	*x = L8TypeList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8TypeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8TypeList) ProtoMessage() {}

func (x *L8TypeList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8TypeList.ProtoReflect.Descriptor instead.
func (*L8TypeList) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *L8TypeList) GetList() []string {
	if x != nil {
		return x.List
	}
	return nil
}

// L8TFASetup is a request to set up two-factor authentication for a user.
type L8TFASetup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The user ID to set up TFA for
	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *L8TFASetup) Reset() {
	*x = L8TFASetup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8TFASetup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8TFASetup) ProtoMessage() {}

func (x *L8TFASetup) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8TFASetup.ProtoReflect.Descriptor instead.
func (*L8TFASetup) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *L8TFASetup) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// L8TFASetupR is the response to a TFA setup request.
// Contains the secret and QR code for authenticator app configuration.
type L8TFASetupR struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The TOTP secret key (base32 encoded)
	Secret string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	// QR code image bytes for scanning with authenticator app
	Qr []byte `protobuf:"bytes,2,opt,name=qr,proto3" json:"qr,omitempty"`
	// Error message if setup failed
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *L8TFASetupR) Reset() {
	*x = L8TFASetupR{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8TFASetupR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8TFASetupR) ProtoMessage() {}

func (x *L8TFASetupR) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8TFASetupR.ProtoReflect.Descriptor instead.
func (*L8TFASetupR) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *L8TFASetupR) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *L8TFASetupR) GetQr() []byte {
	if x != nil {
		return x.Qr
	}
	return nil
}

func (x *L8TFASetupR) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// L8TFAVerify is a request to verify a two-factor authentication code.
type L8TFAVerify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The user ID being verified
	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	// The TOTP code from the authenticator app
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// Bearer token from initial authentication
	Bearer string `protobuf:"bytes,3,opt,name=bearer,proto3" json:"bearer,omitempty"`
}

func (x *L8TFAVerify) Reset() {
	*x = L8TFAVerify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8TFAVerify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8TFAVerify) ProtoMessage() {}

func (x *L8TFAVerify) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8TFAVerify.ProtoReflect.Descriptor instead.
func (*L8TFAVerify) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *L8TFAVerify) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *L8TFAVerify) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *L8TFAVerify) GetBearer() string {
	if x != nil {
		return x.Bearer
	}
	return ""
}

// L8TFAVerifyR is the response to a TFA verification request.
type L8TFAVerifyR struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// True if the code was valid and verification succeeded
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *L8TFAVerifyR) Reset() {
	*x = L8TFAVerifyR{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8TFAVerifyR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8TFAVerifyR) ProtoMessage() {}

func (x *L8TFAVerifyR) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8TFAVerifyR.ProtoReflect.Descriptor instead.
func (*L8TFAVerifyR) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *L8TFAVerifyR) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// Captcha contains captcha challenge data for bot protection.
type Captcha struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Captcha image or challenge data bytes
	Captcha []byte `protobuf:"bytes,1,opt,name=captcha,proto3" json:"captcha,omitempty"`
}

func (x *Captcha) Reset() {
	*x = Captcha{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Captcha) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Captcha) ProtoMessage() {}

func (x *Captcha) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Captcha.ProtoReflect.Descriptor instead.
func (*Captcha) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *Captcha) GetCaptcha() []byte {
	if x != nil {
		return x.Captcha
	}
	return nil
}

// L8Credential represents a single credential with multiple sides/components.
// Used for storing complex credentials like connection strings or API keys.
type L8Credential struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// First component of the credential (e.g., host, username)
	Aside string `protobuf:"bytes,1,opt,name=aside,proto3" json:"aside,omitempty"`
	// Second component of the credential (e.g., port, password)
	Zside string `protobuf:"bytes,2,opt,name=zside,proto3" json:"zside,omitempty"`
	// Third component of the credential (e.g., database, token)
	Yside string `protobuf:"bytes,3,opt,name=yside,proto3" json:"yside,omitempty"`
}

func (x *L8Credential) Reset() {
	*x = L8Credential{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8Credential) ProtoMessage() {}

func (x *L8Credential) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8Credential.ProtoReflect.Descriptor instead.
func (*L8Credential) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *L8Credential) GetAside() string {
	if x != nil {
		return x.Aside
	}
	return ""
}

func (x *L8Credential) GetZside() string {
	if x != nil {
		return x.Zside
	}
	return ""
}

func (x *L8Credential) GetYside() string {
	if x != nil {
		return x.Yside
	}
	return ""
}

// L8CredentialsList is a paginated list of credentials with metadata.
type L8CredentialsList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of credential sets
	List []*L8Credentials `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// Metadata for the result set
	Metadata *L8MetaData `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *L8CredentialsList) Reset() {
	*x = L8CredentialsList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8CredentialsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8CredentialsList) ProtoMessage() {}

func (x *L8CredentialsList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8CredentialsList.ProtoReflect.Descriptor instead.
func (*L8CredentialsList) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{15}
}

func (x *L8CredentialsList) GetList() []*L8Credentials {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *L8CredentialsList) GetMetadata() *L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// L8Credentials represents a named set of credentials.
// Groups related credentials under a single identifier.
type L8Credentials struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique identifier for this credential set
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable name for the credential set
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Map of credential key to credential value
	Creds map[string]*L8Credential `protobuf:"bytes,3,rep,name=creds,proto3" json:"creds,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *L8Credentials) Reset() {
	*x = L8Credentials{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8Credentials) ProtoMessage() {}

func (x *L8Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8Credentials.ProtoReflect.Descriptor instead.
func (*L8Credentials) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{16}
}

func (x *L8Credentials) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *L8Credentials) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *L8Credentials) GetCreds() map[string]*L8Credential {
	if x != nil {
		return x.Creds
	}
	return nil
}

// L8CredentialsMask represents credentials with masked/encrypted values.
// Used for secure transmission of credential data.
type L8CredentialsMask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique identifier for the credential set
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Encrypted or masked credential data
	Creds []byte `protobuf:"bytes,2,opt,name=creds,proto3" json:"creds,omitempty"`
}

func (x *L8CredentialsMask) Reset() {
	*x = L8CredentialsMask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8CredentialsMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8CredentialsMask) ProtoMessage() {}

func (x *L8CredentialsMask) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8CredentialsMask.ProtoReflect.Descriptor instead.
func (*L8CredentialsMask) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{17}
}

func (x *L8CredentialsMask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *L8CredentialsMask) GetCreds() []byte {
	if x != nil {
		return x.Creds
	}
	return nil
}

type L8Period struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeriodType  L8PeriodType  `protobuf:"varint,1,opt,name=period_type,json=periodType,proto3,enum=l8api.L8PeriodType" json:"period_type,omitempty"`
	PeriodYear  int32         `protobuf:"varint,2,opt,name=period_year,json=periodYear,proto3" json:"period_year,omitempty"`
	PeriodValue L8PeriodValue `protobuf:"varint,3,opt,name=period_value,json=periodValue,proto3,enum=l8api.L8PeriodValue" json:"period_value,omitempty"`
}

func (x *L8Period) Reset() {
	*x = L8Period{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8Period) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8Period) ProtoMessage() {}

func (x *L8Period) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8Period.ProtoReflect.Descriptor instead.
func (*L8Period) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{18}
}

func (x *L8Period) GetPeriodType() L8PeriodType {
	if x != nil {
		return x.PeriodType
	}
	return L8PeriodType_invalid_period_type
}

func (x *L8Period) GetPeriodYear() int32 {
	if x != nil {
		return x.PeriodYear
	}
	return 0
}

func (x *L8Period) GetPeriodValue() L8PeriodValue {
	if x != nil {
		return x.PeriodValue
	}
	return L8PeriodValue_invalid_period_value
}

var File_api_proto protoreflect.FileDescriptor

var file_api_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c, 0x38, 0x61,
	0x70, 0x69, 0x22, 0xc3, 0x02, 0x0a, 0x07, 0x4c, 0x38, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x2f,
	0x0a, 0x08, 0x63, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x45, 0x78, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x63, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x12,
	0x17, 0x0a, 0x07, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x62, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x73, 0x63,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x64, 0x65,
	0x73, 0x63, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x63, 0x61, 0x73, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x43, 0x61, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x70,
	0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x6d,
	0x61, 0x70, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x22, 0xab, 0x01, 0x0a, 0x0c, 0x4c, 0x38, 0x45,
	0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x09, 0x63, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6c,
	0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x61,
	0x6e, 0x64, 0x5f, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6e, 0x64,
	0x4f, 0x72, 0x12, 0x27, 0x0a, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x45, 0x78, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x12, 0x29, 0x0a, 0x05, 0x63,
	0x68, 0x69, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x38, 0x61,
	0x70, 0x69, 0x2e, 0x4c, 0x38, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x05, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x22, 0x7e, 0x0a, 0x0b, 0x4c, 0x38, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x38, 0x61, 0x70,
	0x69, 0x2e, 0x4c, 0x38, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x0a,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x72, 0x12, 0x26,
	0x0a, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6c,
	0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x22, 0x4c, 0x0a, 0x0c, 0x4c, 0x38, 0x43, 0x6f, 0x6d, 0x70,
	0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72,
	0x69, 0x67, 0x68, 0x74, 0x22, 0x4c, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x70, 0x74,
	0x63, 0x68, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x70, 0x74, 0x63,
	0x68, 0x61, 0x22, 0x6f, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x65, 0x74, 0x75, 0x70, 0x5f, 0x74, 0x66, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x73, 0x65, 0x74, 0x75, 0x70, 0x54, 0x66, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x65, 0x65, 0x64,
	0x5f, 0x74, 0x66, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6e, 0x65, 0x65, 0x64,
	0x54, 0x66, 0x61, 0x22, 0xcc, 0x01, 0x0a, 0x0a, 0x4c, 0x38, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x2b, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x42, 0x0a, 0x0b, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x4d,
	0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x1a, 0x4d, 0x0a, 0x0f, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e,
	0x4c, 0x38, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x78, 0x0a, 0x07, 0x4c, 0x38, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x32, 0x0a,
	0x06, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x20, 0x0a, 0x0a,
	0x4c, 0x38, 0x54, 0x79, 0x70, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x24,
	0x0a, 0x0a, 0x4c, 0x38, 0x54, 0x46, 0x41, 0x53, 0x65, 0x74, 0x75, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x4b, 0x0a, 0x0b, 0x4c, 0x38, 0x54, 0x46, 0x41, 0x53, 0x65, 0x74,
	0x75, 0x70, 0x52, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x71,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x71, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x51, 0x0a, 0x0b, 0x4c, 0x38, 0x54, 0x46, 0x41, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x65, 0x61, 0x72, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x65,
	0x61, 0x72, 0x65, 0x72, 0x22, 0x1e, 0x0a, 0x0c, 0x4c, 0x38, 0x54, 0x46, 0x41, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x52, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x6f, 0x6b, 0x22, 0x23, 0x0a, 0x07, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x22, 0x50, 0x0a, 0x0c, 0x4c, 0x38, 0x43,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x73, 0x69,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x73, 0x69, 0x64, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x7a, 0x73, 0x69, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x7a, 0x73, 0x69, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x79, 0x73, 0x69, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x79, 0x73, 0x69, 0x64, 0x65, 0x22, 0x6c, 0x0a, 0x11, 0x4c,
	0x38, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x28, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c,
	0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0xb9, 0x01, 0x0a, 0x0d, 0x4c, 0x38,
	0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x35, 0x0a, 0x05, 0x63, 0x72, 0x65, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x05, 0x63, 0x72, 0x65, 0x64, 0x73, 0x1a, 0x4d, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x64, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38,
	0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x39, 0x0a, 0x11, 0x4c, 0x38, 0x43, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x72,
	0x65, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x63, 0x72, 0x65, 0x64, 0x73,
	0x22, 0x9a, 0x01, 0x0a, 0x08, 0x4c, 0x38, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x34, 0x0a,
	0x0b, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x50, 0x65, 0x72,
	0x69, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x5f, 0x79, 0x65,
	0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x59, 0x65, 0x61, 0x72, 0x12, 0x37, 0x0a, 0x0c, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6c, 0x38, 0x61,
	0x70, 0x69, 0x2e, 0x4c, 0x38, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x0b, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2a, 0x4f, 0x0a,
	0x0c, 0x4c, 0x38, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a,
	0x13, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x59, 0x65, 0x61, 0x72, 0x6c, 0x79,
	0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x51, 0x75, 0x61, 0x72, 0x74, 0x65, 0x72, 0x6c, 0x79, 0x10,
	0x02, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x6c, 0x79, 0x10, 0x03, 0x2a, 0xdb,
	0x01, 0x0a, 0x0d, 0x4c, 0x38, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x18, 0x0a, 0x14, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x70, 0x65, 0x72, 0x69,
	0x6f, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4a, 0x61,
	0x6e, 0x75, 0x61, 0x72, 0x79, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x65, 0x62, 0x72, 0x75,
	0x61, 0x72, 0x79, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x61, 0x72, 0x63, 0x68, 0x10, 0x03,
	0x12, 0x09, 0x0a, 0x05, 0x41, 0x70, 0x72, 0x69, 0x6c, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x4d,
	0x61, 0x79, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x75, 0x6e, 0x65, 0x10, 0x06, 0x12, 0x08,
	0x0a, 0x04, 0x4a, 0x75, 0x6c, 0x79, 0x10, 0x07, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x75, 0x67, 0x75,
	0x73, 0x74, 0x10, 0x08, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x65, 0x70, 0x74, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x10, 0x09, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x63, 0x74, 0x6f, 0x62, 0x65, 0x72, 0x10, 0x0a,
	0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x6f, 0x76, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x10, 0x0b, 0x12, 0x0c,
	0x0a, 0x08, 0x44, 0x65, 0x63, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x10, 0x0c, 0x12, 0x06, 0x0a, 0x02,
	0x51, 0x31, 0x10, 0x0d, 0x12, 0x06, 0x0a, 0x02, 0x51, 0x32, 0x10, 0x0e, 0x12, 0x06, 0x0a, 0x02,
	0x51, 0x33, 0x10, 0x0f, 0x12, 0x06, 0x0a, 0x02, 0x51, 0x34, 0x10, 0x10, 0x42, 0x29, 0x0a, 0x0f,
	0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x42,
	0x05, 0x4c, 0x38, 0x41, 0x70, 0x69, 0x50, 0x01, 0x5a, 0x0d, 0x2e, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2f, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData = file_api_proto_rawDesc
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_rawDescData)
	})
	return file_api_proto_rawDescData
}

var file_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_proto_goTypes = []interface{}{
	(L8PeriodType)(0),         // 0: l8api.L8PeriodType
	(L8PeriodValue)(0),        // 1: l8api.L8PeriodValue
	(*L8Query)(nil),           // 2: l8api.L8Query
	(*L8Expression)(nil),      // 3: l8api.L8Expression
	(*L8Condition)(nil),       // 4: l8api.L8Condition
	(*L8Comparator)(nil),      // 5: l8api.L8Comparator
	(*AuthUser)(nil),          // 6: l8api.AuthUser
	(*AuthToken)(nil),         // 7: l8api.AuthToken
	(*L8MetaData)(nil),        // 8: l8api.L8MetaData
	(*L8Count)(nil),           // 9: l8api.L8Count
	(*L8TypeList)(nil),        // 10: l8api.L8TypeList
	(*L8TFASetup)(nil),        // 11: l8api.L8TFASetup
	(*L8TFASetupR)(nil),       // 12: l8api.L8TFASetupR
	(*L8TFAVerify)(nil),       // 13: l8api.L8TFAVerify
	(*L8TFAVerifyR)(nil),      // 14: l8api.L8TFAVerifyR
	(*Captcha)(nil),           // 15: l8api.Captcha
	(*L8Credential)(nil),      // 16: l8api.L8Credential
	(*L8CredentialsList)(nil), // 17: l8api.L8CredentialsList
	(*L8Credentials)(nil),     // 18: l8api.L8Credentials
	(*L8CredentialsMask)(nil), // 19: l8api.L8CredentialsMask
	(*L8Period)(nil),          // 20: l8api.L8Period
	nil,                       // 21: l8api.L8MetaData.ValueCountEntry
	nil,                       // 22: l8api.L8Count.CountsEntry
	nil,                       // 23: l8api.L8Credentials.CredsEntry
}
var file_api_proto_depIdxs = []int32{
	3,  // 0: l8api.L8Query.criteria:type_name -> l8api.L8Expression
	4,  // 1: l8api.L8Expression.condition:type_name -> l8api.L8Condition
	3,  // 2: l8api.L8Expression.next:type_name -> l8api.L8Expression
	3,  // 3: l8api.L8Expression.child:type_name -> l8api.L8Expression
	5,  // 4: l8api.L8Condition.comparator:type_name -> l8api.L8Comparator
	4,  // 5: l8api.L8Condition.next:type_name -> l8api.L8Condition
	9,  // 6: l8api.L8MetaData.key_count:type_name -> l8api.L8Count
	21, // 7: l8api.L8MetaData.value_count:type_name -> l8api.L8MetaData.ValueCountEntry
	22, // 8: l8api.L8Count.counts:type_name -> l8api.L8Count.CountsEntry
	18, // 9: l8api.L8CredentialsList.list:type_name -> l8api.L8Credentials
	8,  // 10: l8api.L8CredentialsList.metadata:type_name -> l8api.L8MetaData
	23, // 11: l8api.L8Credentials.creds:type_name -> l8api.L8Credentials.CredsEntry
	0,  // 12: l8api.L8Period.period_type:type_name -> l8api.L8PeriodType
	1,  // 13: l8api.L8Period.period_value:type_name -> l8api.L8PeriodValue
	9,  // 14: l8api.L8MetaData.ValueCountEntry.value:type_name -> l8api.L8Count
	16, // 15: l8api.L8Credentials.CredsEntry.value:type_name -> l8api.L8Credential
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8Expression); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8Condition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8Comparator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8MetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8Count); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8TypeList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8TFASetup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8TFASetupR); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8TFAVerify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8TFAVerifyR); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Captcha); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8Credential); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8CredentialsList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8Credentials); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8CredentialsMask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8Period); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		EnumInfos:         file_api_proto_enumTypes,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_rawDesc = nil
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
