// © 2025 Sharon Aicler (saichler@gmail.com)
//
// Layer 8 Ecosystem is licensed under the Apache License, Version 2.0.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// reflect.proto defines types for runtime type introspection and reflection.
// Enables dynamic type inspection, field decoration, and table view generation
// for building adaptive UIs and data processing pipelines.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: reflect.proto

package l8reflect

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// L8DecoratorType enumerates the available field decorator types.
// Decorators control indexing, UI rendering, and serialization behavior.
type L8DecoratorType int32

const (
	// Invalid or unspecified decorator
	L8DecoratorType_Invalid L8DecoratorType = 0
	// Primary key field - used for unique identification
	L8DecoratorType_Primary L8DecoratorType = 1
	// Unique field - enforces uniqueness constraint
	L8DecoratorType_Unique L8DecoratorType = 2
	// Non-unique indexed field - for efficient lookups without uniqueness
	L8DecoratorType_NonUnique L8DecoratorType = 3
	// Display title field - shown as the entity label in UIs
	L8DecoratorType_Title L8DecoratorType = 4
	// Editor hint - specifies custom editor component
	L8DecoratorType_Editor L8DecoratorType = 5
	// Skip nested inspection - don't recurse into this field
	L8DecoratorType_NoNestedInspection L8DecoratorType = 6
	// Completely ignore this field in processing
	L8DecoratorType_Ignore L8DecoratorType = 7
	// Ignore specific attributes within this field
	L8DecoratorType_IgnoreAttr L8DecoratorType = 8
	// Always serialize/send the full value (no delta compression)
	L8DecoratorType_AlwaysFull L8DecoratorType = 9
)

// Enum value maps for L8DecoratorType.
var (
	L8DecoratorType_name = map[int32]string{
		0: "Invalid",
		1: "Primary",
		2: "Unique",
		3: "NonUnique",
		4: "Title",
		5: "Editor",
		6: "NoNestedInspection",
		7: "Ignore",
		8: "IgnoreAttr",
		9: "AlwaysFull",
	}
	L8DecoratorType_value = map[string]int32{
		"Invalid":            0,
		"Primary":            1,
		"Unique":             2,
		"NonUnique":          3,
		"Title":              4,
		"Editor":             5,
		"NoNestedInspection": 6,
		"Ignore":             7,
		"IgnoreAttr":         8,
		"AlwaysFull":         9,
	}
)

func (x L8DecoratorType) Enum() *L8DecoratorType {
	p := new(L8DecoratorType)
	*p = x
	return p
}

func (x L8DecoratorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L8DecoratorType) Descriptor() protoreflect.EnumDescriptor {
	return file_reflect_proto_enumTypes[0].Descriptor()
}

func (L8DecoratorType) Type() protoreflect.EnumType {
	return &file_reflect_proto_enumTypes[0]
}

func (x L8DecoratorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use L8DecoratorType.Descriptor instead.
func (L8DecoratorType) EnumDescriptor() ([]byte, []int) {
	return file_reflect_proto_rawDescGZIP(), []int{0}
}

// L8Node represents a node in the type reflection tree.
// Describes the structure of a type including its fields, nested types, and decorators.
type L8Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type name. For maps, this is the value type.
	TypeName string `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	// For maps or slices, this is the key/index type
	KeyTypeName string `protobuf:"bytes,2,opt,name=key_type_name,json=keyTypeName,proto3" json:"key_type_name,omitempty"`
	// Reference to the parent node (nil for root)
	Parent *L8Node `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	// The field name in the parent type
	FieldName string `protobuf:"bytes,4,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	// For struct types, maps field names to their child nodes
	Attributes map[string]*L8Node `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// True if this field is a map type
	IsMap bool `protobuf:"varint,6,opt,name=is_map,json=isMap,proto3" json:"is_map,omitempty"`
	// True if this field is a slice/array type
	IsSlice bool `protobuf:"varint,7,opt,name=is_slice,json=isSlice,proto3" json:"is_slice,omitempty"`
	// Cached unique key for efficient lookups
	CachedKey string `protobuf:"bytes,8,opt,name=cached_key,json=cachedKey,proto3" json:"cached_key,omitempty"`
	// Field decorators keyed by decorator type ordinal
	Decorators map[int32]*L8Decorator `protobuf:"bytes,9,rep,name=decorators,proto3" json:"decorators,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// True if this is a struct type or contains structs
	IsStruct      bool `protobuf:"varint,10,opt,name=is_struct,json=isStruct,proto3" json:"is_struct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8Node) Reset() {
	*x = L8Node{}
	mi := &file_reflect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8Node) ProtoMessage() {}

func (x *L8Node) ProtoReflect() protoreflect.Message {
	mi := &file_reflect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8Node.ProtoReflect.Descriptor instead.
func (*L8Node) Descriptor() ([]byte, []int) {
	return file_reflect_proto_rawDescGZIP(), []int{0}
}

func (x *L8Node) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *L8Node) GetKeyTypeName() string {
	if x != nil {
		return x.KeyTypeName
	}
	return ""
}

func (x *L8Node) GetParent() *L8Node {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *L8Node) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *L8Node) GetAttributes() map[string]*L8Node {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *L8Node) GetIsMap() bool {
	if x != nil {
		return x.IsMap
	}
	return false
}

func (x *L8Node) GetIsSlice() bool {
	if x != nil {
		return x.IsSlice
	}
	return false
}

func (x *L8Node) GetCachedKey() string {
	if x != nil {
		return x.CachedKey
	}
	return ""
}

func (x *L8Node) GetDecorators() map[int32]*L8Decorator {
	if x != nil {
		return x.Decorators
	}
	return nil
}

func (x *L8Node) GetIsStruct() bool {
	if x != nil {
		return x.IsStruct
	}
	return false
}

// L8Decorator contains decorator metadata for a field.
// Decorators provide hints for UI rendering, indexing, and validation.
type L8Decorator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of field names or values associated with this decorator
	Fields        []string `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8Decorator) Reset() {
	*x = L8Decorator{}
	mi := &file_reflect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8Decorator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8Decorator) ProtoMessage() {}

func (x *L8Decorator) ProtoReflect() protoreflect.Message {
	mi := &file_reflect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8Decorator.ProtoReflect.Descriptor instead.
func (*L8Decorator) Descriptor() ([]byte, []int) {
	return file_reflect_proto_rawDescGZIP(), []int{1}
}

func (x *L8Decorator) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// L8TableView defines a table structure for displaying hierarchical data.
// Used for generating UI components and export formats.
type L8TableView struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The root node defining the table structure
	Table *L8Node `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	// Column definitions for the table
	Columns []*L8Node `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	// Nested sub-tables for hierarchical data
	SubTables     []*L8Node `protobuf:"bytes,3,rep,name=sub_tables,json=subTables,proto3" json:"sub_tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8TableView) Reset() {
	*x = L8TableView{}
	mi := &file_reflect_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8TableView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8TableView) ProtoMessage() {}

func (x *L8TableView) ProtoReflect() protoreflect.Message {
	mi := &file_reflect_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8TableView.ProtoReflect.Descriptor instead.
func (*L8TableView) Descriptor() ([]byte, []int) {
	return file_reflect_proto_rawDescGZIP(), []int{2}
}

func (x *L8TableView) GetTable() *L8Node {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *L8TableView) GetColumns() []*L8Node {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *L8TableView) GetSubTables() []*L8Node {
	if x != nil {
		return x.SubTables
	}
	return nil
}

var File_reflect_proto protoreflect.FileDescriptor

const file_reflect_proto_rawDesc = "" +
	"\n" +
	"\rreflect.proto\x12\tl8reflect\"\xb0\x04\n" +
	"\x06L8Node\x12\x1b\n" +
	"\ttype_name\x18\x01 \x01(\tR\btypeName\x12\"\n" +
	"\rkey_type_name\x18\x02 \x01(\tR\vkeyTypeName\x12)\n" +
	"\x06parent\x18\x03 \x01(\v2\x11.l8reflect.L8NodeR\x06parent\x12\x1d\n" +
	"\n" +
	"field_name\x18\x04 \x01(\tR\tfieldName\x12A\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2!.l8reflect.L8Node.AttributesEntryR\n" +
	"attributes\x12\x15\n" +
	"\x06is_map\x18\x06 \x01(\bR\x05isMap\x12\x19\n" +
	"\bis_slice\x18\a \x01(\bR\aisSlice\x12\x1d\n" +
	"\n" +
	"cached_key\x18\b \x01(\tR\tcachedKey\x12A\n" +
	"\n" +
	"decorators\x18\t \x03(\v2!.l8reflect.L8Node.DecoratorsEntryR\n" +
	"decorators\x12\x1b\n" +
	"\tis_struct\x18\n" +
	" \x01(\bR\bisStruct\x1aP\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.l8reflect.L8NodeR\x05value:\x028\x01\x1aU\n" +
	"\x0fDecoratorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.l8reflect.L8DecoratorR\x05value:\x028\x01\"%\n" +
	"\vL8Decorator\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fields\"\x95\x01\n" +
	"\vL8TableView\x12'\n" +
	"\x05table\x18\x01 \x01(\v2\x11.l8reflect.L8NodeR\x05table\x12+\n" +
	"\acolumns\x18\x02 \x03(\v2\x11.l8reflect.L8NodeR\acolumns\x120\n" +
	"\n" +
	"sub_tables\x18\x03 \x03(\v2\x11.l8reflect.L8NodeR\tsubTables*\xa1\x01\n" +
	"\x0fL8DecoratorType\x12\v\n" +
	"\aInvalid\x10\x00\x12\v\n" +
	"\aPrimary\x10\x01\x12\n" +
	"\n" +
	"\x06Unique\x10\x02\x12\r\n" +
	"\tNonUnique\x10\x03\x12\t\n" +
	"\x05Title\x10\x04\x12\n" +
	"\n" +
	"\x06Editor\x10\x05\x12\x16\n" +
	"\x12NoNestedInspection\x10\x06\x12\n" +
	"\n" +
	"\x06Ignore\x10\a\x12\x0e\n" +
	"\n" +
	"IgnoreAttr\x10\b\x12\x0e\n" +
	"\n" +
	"AlwaysFull\x10\tB5\n" +
	"\x13com.types.l8reflectB\tL8ReflectP\x01Z\x11./types/l8reflectb\x06proto3"

var (
	file_reflect_proto_rawDescOnce sync.Once
	file_reflect_proto_rawDescData []byte
)

func file_reflect_proto_rawDescGZIP() []byte {
	file_reflect_proto_rawDescOnce.Do(func() {
		file_reflect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reflect_proto_rawDesc), len(file_reflect_proto_rawDesc)))
	})
	return file_reflect_proto_rawDescData
}

var file_reflect_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_reflect_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_reflect_proto_goTypes = []any{
	(L8DecoratorType)(0), // 0: l8reflect.L8DecoratorType
	(*L8Node)(nil),       // 1: l8reflect.L8Node
	(*L8Decorator)(nil),  // 2: l8reflect.L8Decorator
	(*L8TableView)(nil),  // 3: l8reflect.L8TableView
	nil,                  // 4: l8reflect.L8Node.AttributesEntry
	nil,                  // 5: l8reflect.L8Node.DecoratorsEntry
}
var file_reflect_proto_depIdxs = []int32{
	1, // 0: l8reflect.L8Node.parent:type_name -> l8reflect.L8Node
	4, // 1: l8reflect.L8Node.attributes:type_name -> l8reflect.L8Node.AttributesEntry
	5, // 2: l8reflect.L8Node.decorators:type_name -> l8reflect.L8Node.DecoratorsEntry
	1, // 3: l8reflect.L8TableView.table:type_name -> l8reflect.L8Node
	1, // 4: l8reflect.L8TableView.columns:type_name -> l8reflect.L8Node
	1, // 5: l8reflect.L8TableView.sub_tables:type_name -> l8reflect.L8Node
	1, // 6: l8reflect.L8Node.AttributesEntry.value:type_name -> l8reflect.L8Node
	2, // 7: l8reflect.L8Node.DecoratorsEntry.value:type_name -> l8reflect.L8Decorator
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_reflect_proto_init() }
func file_reflect_proto_init() {
	if File_reflect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reflect_proto_rawDesc), len(file_reflect_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reflect_proto_goTypes,
		DependencyIndexes: file_reflect_proto_depIdxs,
		EnumInfos:         file_reflect_proto_enumTypes,
		MessageInfos:      file_reflect_proto_msgTypes,
	}.Build()
	File_reflect_proto = out.File
	file_reflect_proto_goTypes = nil
	file_reflect_proto_depIdxs = nil
}
