// © 2025 Sharon Aicler (saichler@gmail.com)
//
// Layer 8 Ecosystem is licensed under the Apache License, Version 2.0.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// notification.proto defines types for property change notifications in the Layer 8 system.
// Enables real-time data synchronization by broadcasting changes to subscribed clients.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: notification.proto

package l8notify

import (
	l8api "github.com/saichler/l8types/go/types/l8api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// L8NotificationType represents the type of change operation that triggered a notification.
type L8NotificationType int32

const (
	// Invalid or unspecified notification type
	L8NotificationType_Invalid_Notify L8NotificationType = 0
	// New entity was created
	L8NotificationType_Post L8NotificationType = 1
	// Entity was fully replaced
	L8NotificationType_Put L8NotificationType = 2
	// Entity was partially updated
	L8NotificationType_Patch L8NotificationType = 3
	// Entity was deleted
	L8NotificationType_Delete L8NotificationType = 4
)

// Enum value maps for L8NotificationType.
var (
	L8NotificationType_name = map[int32]string{
		0: "Invalid_Notify",
		1: "Post",
		2: "Put",
		3: "Patch",
		4: "Delete",
	}
	L8NotificationType_value = map[string]int32{
		"Invalid_Notify": 0,
		"Post":           1,
		"Put":            2,
		"Patch":          3,
		"Delete":         4,
	}
)

func (x L8NotificationType) Enum() *L8NotificationType {
	p := new(L8NotificationType)
	*p = x
	return p
}

func (x L8NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L8NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[0].Descriptor()
}

func (L8NotificationType) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[0]
}

func (x L8NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use L8NotificationType.Descriptor instead.
func (L8NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

// L8NotificationSet groups multiple property change notifications for a single entity.
// Provides batched delivery of changes for efficiency.
type L8NotificationSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source identifier (typically the UUID of the originating node)
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// Timestamp when the changes occurred (Unix millis)
	Time int64 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	// Sequence number for ordering notifications
	Sequence uint32 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Name of the service that owns this data
	ServiceName string `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Service area where the change occurred
	ServiceArea int32 `protobuf:"varint,5,opt,name=service_area,json=serviceArea,proto3" json:"service_area,omitempty"`
	// Type name of the modified model/entity
	ModelType string `protobuf:"bytes,6,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	// Primary key of the modified model/entity
	ModelKey string `protobuf:"bytes,7,opt,name=model_key,json=modelKey,proto3" json:"model_key,omitempty"`
	// Type of change operation (Post, Put, Patch, Delete)
	Type L8NotificationType `protobuf:"varint,8,opt,name=type,proto3,enum=l8notify.L8NotificationType" json:"type,omitempty"`
	// List of individual property changes
	NotificationList []*L8Notification `protobuf:"bytes,9,rep,name=notification_list,json=notificationList,proto3" json:"notification_list,omitempty"`
	// AAAIds of subscribed clients that should receive this notification
	AaaIds        map[string]bool `protobuf:"bytes,10,rep,name=aaa_ids,json=aaaIds,proto3" json:"aaa_ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8NotificationSet) Reset() {
	*x = L8NotificationSet{}
	mi := &file_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8NotificationSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8NotificationSet) ProtoMessage() {}

func (x *L8NotificationSet) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8NotificationSet.ProtoReflect.Descriptor instead.
func (*L8NotificationSet) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

func (x *L8NotificationSet) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *L8NotificationSet) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *L8NotificationSet) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *L8NotificationSet) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *L8NotificationSet) GetServiceArea() int32 {
	if x != nil {
		return x.ServiceArea
	}
	return 0
}

func (x *L8NotificationSet) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *L8NotificationSet) GetModelKey() string {
	if x != nil {
		return x.ModelKey
	}
	return ""
}

func (x *L8NotificationSet) GetType() L8NotificationType {
	if x != nil {
		return x.Type
	}
	return L8NotificationType_Invalid_Notify
}

func (x *L8NotificationSet) GetNotificationList() []*L8Notification {
	if x != nil {
		return x.NotificationList
	}
	return nil
}

func (x *L8NotificationSet) GetAaaIds() map[string]bool {
	if x != nil {
		return x.AaaIds
	}
	return nil
}

// L8Notification represents a single property change within an entity.
// Contains the old and new values for delta tracking.
type L8Notification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the property that changed
	PropertyId string `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	// Previous value (serialized bytes, empty for new properties)
	OldValue []byte `protobuf:"bytes,2,opt,name=oldValue,proto3" json:"oldValue,omitempty"`
	// New value (serialized bytes, empty for deleted properties)
	NewValue      []byte `protobuf:"bytes,3,opt,name=newValue,proto3" json:"newValue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8Notification) Reset() {
	*x = L8Notification{}
	mi := &file_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8Notification) ProtoMessage() {}

func (x *L8Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8Notification.ProtoReflect.Descriptor instead.
func (*L8Notification) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

func (x *L8Notification) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

func (x *L8Notification) GetOldValue() []byte {
	if x != nil {
		return x.OldValue
	}
	return nil
}

func (x *L8Notification) GetNewValue() []byte {
	if x != nil {
		return x.NewValue
	}
	return nil
}

type L8TSDBNotification struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	PropertyId    string                   `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	Point         *l8api.L8TimeSeriesPoint `protobuf:"bytes,2,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8TSDBNotification) Reset() {
	*x = L8TSDBNotification{}
	mi := &file_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8TSDBNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8TSDBNotification) ProtoMessage() {}

func (x *L8TSDBNotification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8TSDBNotification.ProtoReflect.Descriptor instead.
func (*L8TSDBNotification) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{2}
}

func (x *L8TSDBNotification) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

func (x *L8TSDBNotification) GetPoint() *l8api.L8TimeSeriesPoint {
	if x != nil {
		return x.Point
	}
	return nil
}

var File_notification_proto protoreflect.FileDescriptor

const file_notification_proto_rawDesc = "" +
	"\n" +
	"\x12notification.proto\x12\bl8notify\x1a\tapi.proto\"\xd3\x03\n" +
	"\x11L8NotificationSet\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x03R\x04time\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\rR\bsequence\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\x12!\n" +
	"\fservice_area\x18\x05 \x01(\x05R\vserviceArea\x12\x1d\n" +
	"\n" +
	"model_type\x18\x06 \x01(\tR\tmodelType\x12\x1b\n" +
	"\tmodel_key\x18\a \x01(\tR\bmodelKey\x120\n" +
	"\x04type\x18\b \x01(\x0e2\x1c.l8notify.L8NotificationTypeR\x04type\x12E\n" +
	"\x11notification_list\x18\t \x03(\v2\x18.l8notify.L8NotificationR\x10notificationList\x12@\n" +
	"\aaaa_ids\x18\n" +
	" \x03(\v2'.l8notify.L8NotificationSet.AaaIdsEntryR\x06aaaIds\x1a9\n" +
	"\vAaaIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"i\n" +
	"\x0eL8Notification\x12\x1f\n" +
	"\vproperty_id\x18\x01 \x01(\tR\n" +
	"propertyId\x12\x1a\n" +
	"\boldValue\x18\x02 \x01(\fR\boldValue\x12\x1a\n" +
	"\bnewValue\x18\x03 \x01(\fR\bnewValue\"e\n" +
	"\x12L8TSDBNotification\x12\x1f\n" +
	"\vproperty_id\x18\x01 \x01(\tR\n" +
	"propertyId\x12.\n" +
	"\x05point\x18\x02 \x01(\v2\x18.l8api.L8TimeSeriesPointR\x05point*R\n" +
	"\x12L8NotificationType\x12\x12\n" +
	"\x0eInvalid_Notify\x10\x00\x12\b\n" +
	"\x04Post\x10\x01\x12\a\n" +
	"\x03Put\x10\x02\x12\t\n" +
	"\x05Patch\x10\x03\x12\n" +
	"\n" +
	"\x06Delete\x10\x04B2\n" +
	"\x12com.types.l8notifyB\bL8NotifyP\x01Z\x10./types/l8notifyb\x06proto3"

var (
	file_notification_proto_rawDescOnce sync.Once
	file_notification_proto_rawDescData []byte
)

func file_notification_proto_rawDescGZIP() []byte {
	file_notification_proto_rawDescOnce.Do(func() {
		file_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)))
	})
	return file_notification_proto_rawDescData
}

var file_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_notification_proto_goTypes = []any{
	(L8NotificationType)(0),         // 0: l8notify.L8NotificationType
	(*L8NotificationSet)(nil),       // 1: l8notify.L8NotificationSet
	(*L8Notification)(nil),          // 2: l8notify.L8Notification
	(*L8TSDBNotification)(nil),      // 3: l8notify.L8TSDBNotification
	nil,                             // 4: l8notify.L8NotificationSet.AaaIdsEntry
	(*l8api.L8TimeSeriesPoint)(nil), // 5: l8api.L8TimeSeriesPoint
}
var file_notification_proto_depIdxs = []int32{
	0, // 0: l8notify.L8NotificationSet.type:type_name -> l8notify.L8NotificationType
	2, // 1: l8notify.L8NotificationSet.notification_list:type_name -> l8notify.L8Notification
	4, // 2: l8notify.L8NotificationSet.aaa_ids:type_name -> l8notify.L8NotificationSet.AaaIdsEntry
	5, // 3: l8notify.L8TSDBNotification.point:type_name -> l8api.L8TimeSeriesPoint
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_notification_proto_init() }
func file_notification_proto_init() {
	if File_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notification_proto_goTypes,
		DependencyIndexes: file_notification_proto_depIdxs,
		EnumInfos:         file_notification_proto_enumTypes,
		MessageInfos:      file_notification_proto_msgTypes,
	}.Build()
	File_notification_proto = out.File
	file_notification_proto_goTypes = nil
	file_notification_proto_depIdxs = nil
}
