// © 2025 Sharon Aicler (saichler@gmail.com)
//
// Layer 8 Ecosystem is licensed under the Apache License, Version 2.0.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// health.proto defines types for health monitoring and statistics collection
// in the Layer 8 distributed system. Provides real-time visibility into
// node status, resource usage, and message traffic.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: health.proto

package l8health

import (
	l8api "github.com/saichler/l8types/go/types/l8api"
	l8services "github.com/saichler/l8types/go/types/l8services"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// L8HealthState represents the health status of a node or service.
type L8HealthState int32

const (
	// Invalid or unknown state
	L8HealthState_Invalid_State L8HealthState = 0
	// Node/service is healthy and responding
	L8HealthState_Up L8HealthState = 1
	// Node/service is down (graceful shutdown or failure)
	L8HealthState_Down L8HealthState = 2
	// Node/service cannot be reached (network issue)
	L8HealthState_Unreachable L8HealthState = 3
)

// Enum value maps for L8HealthState.
var (
	L8HealthState_name = map[int32]string{
		0: "Invalid_State",
		1: "Up",
		2: "Down",
		3: "Unreachable",
	}
	L8HealthState_value = map[string]int32{
		"Invalid_State": 0,
		"Up":            1,
		"Down":          2,
		"Unreachable":   3,
	}
)

func (x L8HealthState) Enum() *L8HealthState {
	p := new(L8HealthState)
	*p = x
	return p
}

func (x L8HealthState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L8HealthState) Descriptor() protoreflect.EnumDescriptor {
	return file_health_proto_enumTypes[0].Descriptor()
}

func (L8HealthState) Type() protoreflect.EnumType {
	return &file_health_proto_enumTypes[0]
}

func (x L8HealthState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use L8HealthState.Descriptor instead.
func (L8HealthState) EnumDescriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{0}
}

// L8HealthList is a paginated list of health records with metadata.
type L8HealthList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of health records
	List []*L8Health `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// Metadata for the result set
	Metadata      *l8api.L8MetaData `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8HealthList) Reset() {
	*x = L8HealthList{}
	mi := &file_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8HealthList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8HealthList) ProtoMessage() {}

func (x *L8HealthList) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8HealthList.ProtoReflect.Descriptor instead.
func (*L8HealthList) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{0}
}

func (x *L8HealthList) GetList() []*L8Health {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *L8HealthList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// L8Health contains comprehensive health information for a node.
// Includes identity, services, status, and performance statistics.
type L8Health struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID of the local endpoint (A-side)
	AUuid string `protobuf:"bytes,1,opt,name=a_uuid,json=aUuid,proto3" json:"a_uuid,omitempty"`
	// UUID of the remote endpoint (Z-side)
	ZUuid string `protobuf:"bytes,2,opt,name=z_uuid,json=zUuid,proto3" json:"z_uuid,omitempty"`
	// Human-readable alias for the node
	Alias string `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	// Services provided by this node
	Services *l8services.L8Services `protobuf:"bytes,4,opt,name=services,proto3" json:"services,omitempty"`
	// Current health status
	Status L8HealthState `protobuf:"varint,5,opt,name=status,proto3,enum=l8health.L8HealthState" json:"status,omitempty"`
	// Performance and usage statistics
	Stats *L8HealthStats `protobuf:"bytes,6,opt,name=stats,proto3" json:"stats,omitempty"`
	// Node start time (Unix timestamp in milliseconds)
	StartTime int64 `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// True if this node is a virtual network (VNet) switch
	IsVnet bool `protobuf:"varint,8,opt,name=is_vnet,json=isVnet,proto3" json:"is_vnet,omitempty"`
	// The pprof memory data when explicitly retrieved
	PprofMemory []byte `protobuf:"bytes,9,opt,name=pprof_memory,json=pprofMemory,proto3" json:"pprof_memory,omitempty"`
	// The pprof cpu data when explicitly retrieved
	PprofCpu []byte `protobuf:"bytes,10,opt,name=pprof_cpu,json=pprofCpu,proto3" json:"pprof_cpu,omitempty"`
	// Flag to collect mem data
	PprofCollect  bool `protobuf:"varint,11,opt,name=pprof_collect,json=pprofCollect,proto3" json:"pprof_collect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8Health) Reset() {
	*x = L8Health{}
	mi := &file_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8Health) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8Health) ProtoMessage() {}

func (x *L8Health) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8Health.ProtoReflect.Descriptor instead.
func (*L8Health) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{1}
}

func (x *L8Health) GetAUuid() string {
	if x != nil {
		return x.AUuid
	}
	return ""
}

func (x *L8Health) GetZUuid() string {
	if x != nil {
		return x.ZUuid
	}
	return ""
}

func (x *L8Health) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *L8Health) GetServices() *l8services.L8Services {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *L8Health) GetStatus() L8HealthState {
	if x != nil {
		return x.Status
	}
	return L8HealthState_Invalid_State
}

func (x *L8Health) GetStats() *L8HealthStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *L8Health) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *L8Health) GetIsVnet() bool {
	if x != nil {
		return x.IsVnet
	}
	return false
}

func (x *L8Health) GetPprofMemory() []byte {
	if x != nil {
		return x.PprofMemory
	}
	return nil
}

func (x *L8Health) GetPprofCpu() []byte {
	if x != nil {
		return x.PprofCpu
	}
	return nil
}

func (x *L8Health) GetPprofCollect() bool {
	if x != nil {
		return x.PprofCollect
	}
	return false
}

// L8HealthStats contains performance and resource usage statistics.
type L8HealthStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp of last message received (Unix millis)
	LastMsgTime int64 `protobuf:"varint,1,opt,name=last_msg_time,json=lastMsgTime,proto3" json:"last_msg_time,omitempty"`
	// Total count of messages transmitted
	TxMsgCount int64 `protobuf:"varint,2,opt,name=tx_msg_count,json=txMsgCount,proto3" json:"tx_msg_count,omitempty"`
	// Total bytes of data transmitted
	TxDataCount int64 `protobuf:"varint,3,opt,name=tx_data_count,json=txDataCount,proto3" json:"tx_data_count,omitempty"`
	// Total count of messages received
	RxMsgCount int64 `protobuf:"varint,4,opt,name=rx_msg_count,json=rxMsgCount,proto3" json:"rx_msg_count,omitempty"`
	// Total bytes of data received
	RxDataCont int64 `protobuf:"varint,5,opt,name=rx_data_cont,json=rxDataCont,proto3" json:"rx_data_cont,omitempty"`
	// Current memory usage in bytes
	MemoryUsage uint64 `protobuf:"varint,6,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	// Current CPU usage as percentage (0.0 to 100.0)
	CpuUsage      float64 `protobuf:"fixed64,7,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8HealthStats) Reset() {
	*x = L8HealthStats{}
	mi := &file_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8HealthStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8HealthStats) ProtoMessage() {}

func (x *L8HealthStats) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8HealthStats.ProtoReflect.Descriptor instead.
func (*L8HealthStats) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{2}
}

func (x *L8HealthStats) GetLastMsgTime() int64 {
	if x != nil {
		return x.LastMsgTime
	}
	return 0
}

func (x *L8HealthStats) GetTxMsgCount() int64 {
	if x != nil {
		return x.TxMsgCount
	}
	return 0
}

func (x *L8HealthStats) GetTxDataCount() int64 {
	if x != nil {
		return x.TxDataCount
	}
	return 0
}

func (x *L8HealthStats) GetRxMsgCount() int64 {
	if x != nil {
		return x.RxMsgCount
	}
	return 0
}

func (x *L8HealthStats) GetRxDataCont() int64 {
	if x != nil {
		return x.RxDataCont
	}
	return 0
}

func (x *L8HealthStats) GetMemoryUsage() uint64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *L8HealthStats) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

// L8Top aggregates health information from multiple nodes.
// Provides a cluster-wide view of system health.
type L8Top struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of node UUID to health information
	Healths       map[string]*L8Health `protobuf:"bytes,1,rep,name=healths,proto3" json:"healths,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8Top) Reset() {
	*x = L8Top{}
	mi := &file_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8Top) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8Top) ProtoMessage() {}

func (x *L8Top) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8Top.ProtoReflect.Descriptor instead.
func (*L8Top) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{3}
}

func (x *L8Top) GetHealths() map[string]*L8Health {
	if x != nil {
		return x.Healths
	}
	return nil
}

var File_health_proto protoreflect.FileDescriptor

const file_health_proto_rawDesc = "" +
	"\n" +
	"\fhealth.proto\x12\bl8health\x1a\x0eservices.proto\x1a\tapi.proto\"e\n" +
	"\fL8HealthList\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.l8health.L8HealthR\x04list\x12-\n" +
	"\bmetadata\x18\x02 \x01(\v2\x11.l8api.L8MetaDataR\bmetadata\"\xff\x02\n" +
	"\bL8Health\x12\x15\n" +
	"\x06a_uuid\x18\x01 \x01(\tR\x05aUuid\x12\x15\n" +
	"\x06z_uuid\x18\x02 \x01(\tR\x05zUuid\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x122\n" +
	"\bservices\x18\x04 \x01(\v2\x16.l8services.L8ServicesR\bservices\x12/\n" +
	"\x06status\x18\x05 \x01(\x0e2\x17.l8health.L8HealthStateR\x06status\x12-\n" +
	"\x05stats\x18\x06 \x01(\v2\x17.l8health.L8HealthStatsR\x05stats\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\x03R\tstartTime\x12\x17\n" +
	"\ais_vnet\x18\b \x01(\bR\x06isVnet\x12!\n" +
	"\fpprof_memory\x18\t \x01(\fR\vpprofMemory\x12\x1b\n" +
	"\tpprof_cpu\x18\n" +
	" \x01(\fR\bpprofCpu\x12#\n" +
	"\rpprof_collect\x18\v \x01(\bR\fpprofCollect\"\xfd\x01\n" +
	"\rL8HealthStats\x12\"\n" +
	"\rlast_msg_time\x18\x01 \x01(\x03R\vlastMsgTime\x12 \n" +
	"\ftx_msg_count\x18\x02 \x01(\x03R\n" +
	"txMsgCount\x12\"\n" +
	"\rtx_data_count\x18\x03 \x01(\x03R\vtxDataCount\x12 \n" +
	"\frx_msg_count\x18\x04 \x01(\x03R\n" +
	"rxMsgCount\x12 \n" +
	"\frx_data_cont\x18\x05 \x01(\x03R\n" +
	"rxDataCont\x12!\n" +
	"\fmemory_usage\x18\x06 \x01(\x04R\vmemoryUsage\x12\x1b\n" +
	"\tcpu_usage\x18\a \x01(\x01R\bcpuUsage\"\x8f\x01\n" +
	"\x05L8Top\x126\n" +
	"\ahealths\x18\x01 \x03(\v2\x1c.l8health.L8Top.HealthsEntryR\ahealths\x1aN\n" +
	"\fHealthsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.l8health.L8HealthR\x05value:\x028\x01*E\n" +
	"\rL8HealthState\x12\x11\n" +
	"\rInvalid_State\x10\x00\x12\x06\n" +
	"\x02Up\x10\x01\x12\b\n" +
	"\x04Down\x10\x02\x12\x0f\n" +
	"\vUnreachable\x10\x03B2\n" +
	"\x12com.types.l8healthB\bL8HealthP\x01Z\x10./types/l8healthb\x06proto3"

var (
	file_health_proto_rawDescOnce sync.Once
	file_health_proto_rawDescData []byte
)

func file_health_proto_rawDescGZIP() []byte {
	file_health_proto_rawDescOnce.Do(func() {
		file_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)))
	})
	return file_health_proto_rawDescData
}

var file_health_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_health_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_health_proto_goTypes = []any{
	(L8HealthState)(0),            // 0: l8health.L8HealthState
	(*L8HealthList)(nil),          // 1: l8health.L8HealthList
	(*L8Health)(nil),              // 2: l8health.L8Health
	(*L8HealthStats)(nil),         // 3: l8health.L8HealthStats
	(*L8Top)(nil),                 // 4: l8health.L8Top
	nil,                           // 5: l8health.L8Top.HealthsEntry
	(*l8api.L8MetaData)(nil),      // 6: l8api.L8MetaData
	(*l8services.L8Services)(nil), // 7: l8services.L8Services
}
var file_health_proto_depIdxs = []int32{
	2, // 0: l8health.L8HealthList.list:type_name -> l8health.L8Health
	6, // 1: l8health.L8HealthList.metadata:type_name -> l8api.L8MetaData
	7, // 2: l8health.L8Health.services:type_name -> l8services.L8Services
	0, // 3: l8health.L8Health.status:type_name -> l8health.L8HealthState
	3, // 4: l8health.L8Health.stats:type_name -> l8health.L8HealthStats
	5, // 5: l8health.L8Top.healths:type_name -> l8health.L8Top.HealthsEntry
	2, // 6: l8health.L8Top.HealthsEntry.value:type_name -> l8health.L8Health
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_health_proto_init() }
func file_health_proto_init() {
	if File_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_health_proto_goTypes,
		DependencyIndexes: file_health_proto_depIdxs,
		EnumInfos:         file_health_proto_enumTypes,
		MessageInfos:      file_health_proto_msgTypes,
	}.Build()
	File_health_proto = out.File
	file_health_proto_goTypes = nil
	file_health_proto_depIdxs = nil
}
