// © 2025 Sharon Aicler (saichler@gmail.com)
//
// Layer 8 Ecosystem is licensed under the Apache License, Version 2.0.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: tests.proto

package testtypes

import (
	l8api "github.com/saichler/l8types/go/types/l8api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestEnum int32

const (
	TestEnum_ValueInvalid TestEnum = 0
	TestEnum_ValueOne     TestEnum = 1
	TestEnum_ValueTwo     TestEnum = 2
)

// Enum value maps for TestEnum.
var (
	TestEnum_name = map[int32]string{
		0: "ValueInvalid",
		1: "ValueOne",
		2: "ValueTwo",
	}
	TestEnum_value = map[string]int32{
		"ValueInvalid": 0,
		"ValueOne":     1,
		"ValueTwo":     2,
	}
)

func (x TestEnum) Enum() *TestEnum {
	p := new(TestEnum)
	*p = x
	return p
}

func (x TestEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_tests_proto_enumTypes[0].Descriptor()
}

func (TestEnum) Type() protoreflect.EnumType {
	return &file_tests_proto_enumTypes[0]
}

func (x TestEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestEnum.Descriptor instead.
func (TestEnum) EnumDescriptor() ([]byte, []int) {
	return file_tests_proto_rawDescGZIP(), []int{0}
}

type TestProtoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*TestProto           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata      *l8api.L8MetaData      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestProtoList) Reset() {
	*x = TestProtoList{}
	mi := &file_tests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestProtoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProtoList) ProtoMessage() {}

func (x *TestProtoList) ProtoReflect() protoreflect.Message {
	mi := &file_tests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProtoList.ProtoReflect.Descriptor instead.
func (*TestProtoList) Descriptor() ([]byte, []int) {
	return file_tests_proto_rawDescGZIP(), []int{0}
}

func (x *TestProtoList) GetList() []*TestProto {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *TestProtoList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TestProto struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	MyString           string                   `protobuf:"bytes,1,opt,name=myString,proto3" json:"myString,omitempty"`
	MyInt32            int32                    `protobuf:"varint,2,opt,name=myInt32,proto3" json:"myInt32,omitempty"`
	MyInt64            int64                    `protobuf:"varint,3,opt,name=myInt64,proto3" json:"myInt64,omitempty"`
	MyFloat32          float32                  `protobuf:"fixed32,4,opt,name=myFloat32,proto3" json:"myFloat32,omitempty"`
	MyFloat64          float64                  `protobuf:"fixed64,5,opt,name=myFloat64,proto3" json:"myFloat64,omitempty"`
	MySingle           *TestProtoSub            `protobuf:"bytes,6,opt,name=mySingle,proto3" json:"mySingle,omitempty"`
	MyStringSlice      []string                 `protobuf:"bytes,7,rep,name=myStringSlice,proto3" json:"myStringSlice,omitempty"`
	MyInt32Slice       []int32                  `protobuf:"varint,8,rep,packed,name=myInt32Slice,proto3" json:"myInt32Slice,omitempty"`
	MyModelSlice       []*TestProtoSub          `protobuf:"bytes,9,rep,name=myModelSlice,proto3" json:"myModelSlice,omitempty"`
	MyString2StringMap map[string]string        `protobuf:"bytes,10,rep,name=MyString2StringMap,proto3" json:"MyString2StringMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MyInt32ToInt64Map  map[int32]int64          `protobuf:"bytes,11,rep,name=MyInt32ToInt64Map,proto3" json:"MyInt32ToInt64Map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	MyString2ModelMap  map[string]*TestProtoSub `protobuf:"bytes,12,rep,name=MyString2ModelMap,proto3" json:"MyString2ModelMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MyBool             bool                     `protobuf:"varint,13,opt,name=myBool,proto3" json:"myBool,omitempty"`
	MyEnum             TestEnum                 `protobuf:"varint,14,opt,name=myEnum,proto3,enum=tests.TestEnum" json:"myEnum,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TestProto) Reset() {
	*x = TestProto{}
	mi := &file_tests_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProto) ProtoMessage() {}

func (x *TestProto) ProtoReflect() protoreflect.Message {
	mi := &file_tests_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProto.ProtoReflect.Descriptor instead.
func (*TestProto) Descriptor() ([]byte, []int) {
	return file_tests_proto_rawDescGZIP(), []int{1}
}

func (x *TestProto) GetMyString() string {
	if x != nil {
		return x.MyString
	}
	return ""
}

func (x *TestProto) GetMyInt32() int32 {
	if x != nil {
		return x.MyInt32
	}
	return 0
}

func (x *TestProto) GetMyInt64() int64 {
	if x != nil {
		return x.MyInt64
	}
	return 0
}

func (x *TestProto) GetMyFloat32() float32 {
	if x != nil {
		return x.MyFloat32
	}
	return 0
}

func (x *TestProto) GetMyFloat64() float64 {
	if x != nil {
		return x.MyFloat64
	}
	return 0
}

func (x *TestProto) GetMySingle() *TestProtoSub {
	if x != nil {
		return x.MySingle
	}
	return nil
}

func (x *TestProto) GetMyStringSlice() []string {
	if x != nil {
		return x.MyStringSlice
	}
	return nil
}

func (x *TestProto) GetMyInt32Slice() []int32 {
	if x != nil {
		return x.MyInt32Slice
	}
	return nil
}

func (x *TestProto) GetMyModelSlice() []*TestProtoSub {
	if x != nil {
		return x.MyModelSlice
	}
	return nil
}

func (x *TestProto) GetMyString2StringMap() map[string]string {
	if x != nil {
		return x.MyString2StringMap
	}
	return nil
}

func (x *TestProto) GetMyInt32ToInt64Map() map[int32]int64 {
	if x != nil {
		return x.MyInt32ToInt64Map
	}
	return nil
}

func (x *TestProto) GetMyString2ModelMap() map[string]*TestProtoSub {
	if x != nil {
		return x.MyString2ModelMap
	}
	return nil
}

func (x *TestProto) GetMyBool() bool {
	if x != nil {
		return x.MyBool
	}
	return false
}

func (x *TestProto) GetMyEnum() TestEnum {
	if x != nil {
		return x.MyEnum
	}
	return TestEnum_ValueInvalid
}

type TestProtoSub struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	MyString      string                      `protobuf:"bytes,1,opt,name=myString,proto3" json:"myString,omitempty"`
	MyInt64       int64                       `protobuf:"varint,2,opt,name=myInt64,proto3" json:"myInt64,omitempty"`
	MySubs        map[string]*TestProtoSubSub `protobuf:"bytes,3,rep,name=mySubs,proto3" json:"mySubs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestProtoSub) Reset() {
	*x = TestProtoSub{}
	mi := &file_tests_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestProtoSub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProtoSub) ProtoMessage() {}

func (x *TestProtoSub) ProtoReflect() protoreflect.Message {
	mi := &file_tests_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProtoSub.ProtoReflect.Descriptor instead.
func (*TestProtoSub) Descriptor() ([]byte, []int) {
	return file_tests_proto_rawDescGZIP(), []int{2}
}

func (x *TestProtoSub) GetMyString() string {
	if x != nil {
		return x.MyString
	}
	return ""
}

func (x *TestProtoSub) GetMyInt64() int64 {
	if x != nil {
		return x.MyInt64
	}
	return 0
}

func (x *TestProtoSub) GetMySubs() map[string]*TestProtoSubSub {
	if x != nil {
		return x.MySubs
	}
	return nil
}

type TestProtoSubSub struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MyString      string                 `protobuf:"bytes,1,opt,name=myString,proto3" json:"myString,omitempty"`
	MyInt64       int64                  `protobuf:"varint,2,opt,name=myInt64,proto3" json:"myInt64,omitempty"`
	Int32Map      map[int32]int32        `protobuf:"bytes,3,rep,name=int32Map,proto3" json:"int32Map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestProtoSubSub) Reset() {
	*x = TestProtoSubSub{}
	mi := &file_tests_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestProtoSubSub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProtoSubSub) ProtoMessage() {}

func (x *TestProtoSubSub) ProtoReflect() protoreflect.Message {
	mi := &file_tests_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProtoSubSub.ProtoReflect.Descriptor instead.
func (*TestProtoSubSub) Descriptor() ([]byte, []int) {
	return file_tests_proto_rawDescGZIP(), []int{3}
}

func (x *TestProtoSubSub) GetMyString() string {
	if x != nil {
		return x.MyString
	}
	return ""
}

func (x *TestProtoSubSub) GetMyInt64() int64 {
	if x != nil {
		return x.MyInt64
	}
	return 0
}

func (x *TestProtoSubSub) GetInt32Map() map[int32]int32 {
	if x != nil {
		return x.Int32Map
	}
	return nil
}

var File_tests_proto protoreflect.FileDescriptor

const file_tests_proto_rawDesc = "" +
	"\n" +
	"\vtests.proto\x12\x05tests\x1a\tapi.proto\"d\n" +
	"\rTestProtoList\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.tests.TestProtoR\x04list\x12-\n" +
	"\bmetadata\x18\x02 \x01(\v2\x11.l8api.L8MetaDataR\bmetadata\"\xfc\x06\n" +
	"\tTestProto\x12\x1a\n" +
	"\bmyString\x18\x01 \x01(\tR\bmyString\x12\x18\n" +
	"\amyInt32\x18\x02 \x01(\x05R\amyInt32\x12\x18\n" +
	"\amyInt64\x18\x03 \x01(\x03R\amyInt64\x12\x1c\n" +
	"\tmyFloat32\x18\x04 \x01(\x02R\tmyFloat32\x12\x1c\n" +
	"\tmyFloat64\x18\x05 \x01(\x01R\tmyFloat64\x12/\n" +
	"\bmySingle\x18\x06 \x01(\v2\x13.tests.TestProtoSubR\bmySingle\x12$\n" +
	"\rmyStringSlice\x18\a \x03(\tR\rmyStringSlice\x12\"\n" +
	"\fmyInt32Slice\x18\b \x03(\x05R\fmyInt32Slice\x127\n" +
	"\fmyModelSlice\x18\t \x03(\v2\x13.tests.TestProtoSubR\fmyModelSlice\x12X\n" +
	"\x12MyString2StringMap\x18\n" +
	" \x03(\v2(.tests.TestProto.MyString2StringMapEntryR\x12MyString2StringMap\x12U\n" +
	"\x11MyInt32ToInt64Map\x18\v \x03(\v2'.tests.TestProto.MyInt32ToInt64MapEntryR\x11MyInt32ToInt64Map\x12U\n" +
	"\x11MyString2ModelMap\x18\f \x03(\v2'.tests.TestProto.MyString2ModelMapEntryR\x11MyString2ModelMap\x12\x16\n" +
	"\x06myBool\x18\r \x01(\bR\x06myBool\x12'\n" +
	"\x06myEnum\x18\x0e \x01(\x0e2\x0f.tests.TestEnumR\x06myEnum\x1aE\n" +
	"\x17MyString2StringMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aD\n" +
	"\x16MyInt32ToInt64MapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aY\n" +
	"\x16MyString2ModelMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.tests.TestProtoSubR\x05value:\x028\x01\"\xd0\x01\n" +
	"\fTestProtoSub\x12\x1a\n" +
	"\bmyString\x18\x01 \x01(\tR\bmyString\x12\x18\n" +
	"\amyInt64\x18\x02 \x01(\x03R\amyInt64\x127\n" +
	"\x06mySubs\x18\x03 \x03(\v2\x1f.tests.TestProtoSub.MySubsEntryR\x06mySubs\x1aQ\n" +
	"\vMySubsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.tests.TestProtoSubSubR\x05value:\x028\x01\"\xc6\x01\n" +
	"\x0fTestProtoSubSub\x12\x1a\n" +
	"\bmyString\x18\x01 \x01(\tR\bmyString\x12\x18\n" +
	"\amyInt64\x18\x02 \x01(\x03R\amyInt64\x12@\n" +
	"\bint32Map\x18\x03 \x03(\v2$.tests.TestProtoSubSub.Int32MapEntryR\bint32Map\x1a;\n" +
	"\rInt32MapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01*8\n" +
	"\bTestEnum\x12\x10\n" +
	"\fValueInvalid\x10\x00\x12\f\n" +
	"\bValueOne\x10\x01\x12\f\n" +
	"\bValueTwo\x10\x02B(\n" +
	"\x10com.shared.testsB\x05TestsP\x01Z\v./testtypesb\x06proto3"

var (
	file_tests_proto_rawDescOnce sync.Once
	file_tests_proto_rawDescData []byte
)

func file_tests_proto_rawDescGZIP() []byte {
	file_tests_proto_rawDescOnce.Do(func() {
		file_tests_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_proto_rawDesc), len(file_tests_proto_rawDesc)))
	})
	return file_tests_proto_rawDescData
}

var file_tests_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tests_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_tests_proto_goTypes = []any{
	(TestEnum)(0),            // 0: tests.TestEnum
	(*TestProtoList)(nil),    // 1: tests.TestProtoList
	(*TestProto)(nil),        // 2: tests.TestProto
	(*TestProtoSub)(nil),     // 3: tests.TestProtoSub
	(*TestProtoSubSub)(nil),  // 4: tests.TestProtoSubSub
	nil,                      // 5: tests.TestProto.MyString2StringMapEntry
	nil,                      // 6: tests.TestProto.MyInt32ToInt64MapEntry
	nil,                      // 7: tests.TestProto.MyString2ModelMapEntry
	nil,                      // 8: tests.TestProtoSub.MySubsEntry
	nil,                      // 9: tests.TestProtoSubSub.Int32MapEntry
	(*l8api.L8MetaData)(nil), // 10: l8api.L8MetaData
}
var file_tests_proto_depIdxs = []int32{
	2,  // 0: tests.TestProtoList.list:type_name -> tests.TestProto
	10, // 1: tests.TestProtoList.metadata:type_name -> l8api.L8MetaData
	3,  // 2: tests.TestProto.mySingle:type_name -> tests.TestProtoSub
	3,  // 3: tests.TestProto.myModelSlice:type_name -> tests.TestProtoSub
	5,  // 4: tests.TestProto.MyString2StringMap:type_name -> tests.TestProto.MyString2StringMapEntry
	6,  // 5: tests.TestProto.MyInt32ToInt64Map:type_name -> tests.TestProto.MyInt32ToInt64MapEntry
	7,  // 6: tests.TestProto.MyString2ModelMap:type_name -> tests.TestProto.MyString2ModelMapEntry
	0,  // 7: tests.TestProto.myEnum:type_name -> tests.TestEnum
	8,  // 8: tests.TestProtoSub.mySubs:type_name -> tests.TestProtoSub.MySubsEntry
	9,  // 9: tests.TestProtoSubSub.int32Map:type_name -> tests.TestProtoSubSub.Int32MapEntry
	3,  // 10: tests.TestProto.MyString2ModelMapEntry.value:type_name -> tests.TestProtoSub
	4,  // 11: tests.TestProtoSub.MySubsEntry.value:type_name -> tests.TestProtoSubSub
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_tests_proto_init() }
func file_tests_proto_init() {
	if File_tests_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_proto_rawDesc), len(file_tests_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_proto_goTypes,
		DependencyIndexes: file_tests_proto_depIdxs,
		EnumInfos:         file_tests_proto_enumTypes,
		MessageInfos:      file_tests_proto_msgTypes,
	}.Build()
	File_tests_proto = out.File
	file_tests_proto_goTypes = nil
	file_tests_proto_depIdxs = nil
}
