// © 2025 Sharon Aicler (saichler@gmail.com)
//
// Layer 8 Ecosystem is licensed under the Apache License, Version 2.0.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// api.proto defines the core API types for the Layer 8 distributed system.
// This includes query DSL for data filtering, authentication and authorization,
// two-factor authentication (TFA), captcha support, and credential management.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: business.proto

package l8business

import (
	l8api "github.com/saichler/l8types/go/types/l8api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type L8BusinessLabelList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*L8BusinessLabel     `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata      *l8api.L8MetaData      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8BusinessLabelList) Reset() {
	*x = L8BusinessLabelList{}
	mi := &file_business_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8BusinessLabelList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8BusinessLabelList) ProtoMessage() {}

func (x *L8BusinessLabelList) ProtoReflect() protoreflect.Message {
	mi := &file_business_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8BusinessLabelList.ProtoReflect.Descriptor instead.
func (*L8BusinessLabelList) Descriptor() ([]byte, []int) {
	return file_business_proto_rawDescGZIP(), []int{0}
}

func (x *L8BusinessLabelList) GetList() []*L8BusinessLabel {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *L8BusinessLabelList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type L8BusinessLabel struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LabelId          string                 `protobuf:"bytes,1,opt,name=label_id,json=labelId,proto3" json:"label_id,omitempty"`
	LabelDescription string                 `protobuf:"bytes,2,opt,name=label_description,json=labelDescription,proto3" json:"label_description,omitempty"`
	AuditInfo        *AuditInfo             `protobuf:"bytes,3,opt,name=audit_info,json=auditInfo,proto3" json:"audit_info,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *L8BusinessLabel) Reset() {
	*x = L8BusinessLabel{}
	mi := &file_business_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8BusinessLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8BusinessLabel) ProtoMessage() {}

func (x *L8BusinessLabel) ProtoReflect() protoreflect.Message {
	mi := &file_business_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8BusinessLabel.ProtoReflect.Descriptor instead.
func (*L8BusinessLabel) Descriptor() ([]byte, []int) {
	return file_business_proto_rawDescGZIP(), []int{1}
}

func (x *L8BusinessLabel) GetLabelId() string {
	if x != nil {
		return x.LabelId
	}
	return ""
}

func (x *L8BusinessLabel) GetLabelDescription() string {
	if x != nil {
		return x.LabelDescription
	}
	return ""
}

func (x *L8BusinessLabel) GetAuditInfo() *AuditInfo {
	if x != nil {
		return x.AuditInfo
	}
	return nil
}

type AuditInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     int64                  `protobuf:"varint,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	ModifiedAt    int64                  `protobuf:"varint,3,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	ModifiedBy    string                 `protobuf:"bytes,4,opt,name=modified_by,json=modifiedBy,proto3" json:"modified_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditInfo) Reset() {
	*x = AuditInfo{}
	mi := &file_business_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditInfo) ProtoMessage() {}

func (x *AuditInfo) ProtoReflect() protoreflect.Message {
	mi := &file_business_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditInfo.ProtoReflect.Descriptor instead.
func (*AuditInfo) Descriptor() ([]byte, []int) {
	return file_business_proto_rawDescGZIP(), []int{2}
}

func (x *AuditInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AuditInfo) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *AuditInfo) GetModifiedAt() int64 {
	if x != nil {
		return x.ModifiedAt
	}
	return 0
}

func (x *AuditInfo) GetModifiedBy() string {
	if x != nil {
		return x.ModifiedBy
	}
	return ""
}

type L8BusinessLabels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        map[string]bool        `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8BusinessLabels) Reset() {
	*x = L8BusinessLabels{}
	mi := &file_business_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8BusinessLabels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8BusinessLabels) ProtoMessage() {}

func (x *L8BusinessLabels) ProtoReflect() protoreflect.Message {
	mi := &file_business_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8BusinessLabels.ProtoReflect.Descriptor instead.
func (*L8BusinessLabels) Descriptor() ([]byte, []int) {
	return file_business_proto_rawDescGZIP(), []int{3}
}

func (x *L8BusinessLabels) GetLabels() map[string]bool {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_business_proto protoreflect.FileDescriptor

const file_business_proto_rawDesc = "" +
	"\n" +
	"\x0ebusiness.proto\x12\n" +
	"l8business\x1a\tapi.proto\"u\n" +
	"\x13L8BusinessLabelList\x12/\n" +
	"\x04list\x18\x01 \x03(\v2\x1b.l8business.L8BusinessLabelR\x04list\x12-\n" +
	"\bmetadata\x18\x02 \x01(\v2\x11.l8api.L8MetaDataR\bmetadata\"\x8f\x01\n" +
	"\x0fL8BusinessLabel\x12\x19\n" +
	"\blabel_id\x18\x01 \x01(\tR\alabelId\x12+\n" +
	"\x11label_description\x18\x02 \x01(\tR\x10labelDescription\x124\n" +
	"\n" +
	"audit_info\x18\x03 \x01(\v2\x15.l8business.AuditInfoR\tauditInfo\"\x8b\x01\n" +
	"\tAuditInfo\x12\x1d\n" +
	"\n" +
	"created_at\x18\x01 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy\x12\x1f\n" +
	"\vmodified_at\x18\x03 \x01(\x03R\n" +
	"modifiedAt\x12\x1f\n" +
	"\vmodified_by\x18\x04 \x01(\tR\n" +
	"modifiedBy\"\x8f\x01\n" +
	"\x10L8BusinessLabels\x12@\n" +
	"\x06labels\x18\x01 \x03(\v2(.l8business.L8BusinessLabels.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01B8\n" +
	"\x14com.types.l8businessB\n" +
	"L8BusinessP\x01Z\x12./types/l8businessb\x06proto3"

var (
	file_business_proto_rawDescOnce sync.Once
	file_business_proto_rawDescData []byte
)

func file_business_proto_rawDescGZIP() []byte {
	file_business_proto_rawDescOnce.Do(func() {
		file_business_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_business_proto_rawDesc), len(file_business_proto_rawDesc)))
	})
	return file_business_proto_rawDescData
}

var file_business_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_business_proto_goTypes = []any{
	(*L8BusinessLabelList)(nil), // 0: l8business.L8BusinessLabelList
	(*L8BusinessLabel)(nil),     // 1: l8business.L8BusinessLabel
	(*AuditInfo)(nil),           // 2: l8business.AuditInfo
	(*L8BusinessLabels)(nil),    // 3: l8business.L8BusinessLabels
	nil,                         // 4: l8business.L8BusinessLabels.LabelsEntry
	(*l8api.L8MetaData)(nil),    // 5: l8api.L8MetaData
}
var file_business_proto_depIdxs = []int32{
	1, // 0: l8business.L8BusinessLabelList.list:type_name -> l8business.L8BusinessLabel
	5, // 1: l8business.L8BusinessLabelList.metadata:type_name -> l8api.L8MetaData
	2, // 2: l8business.L8BusinessLabel.audit_info:type_name -> l8business.AuditInfo
	4, // 3: l8business.L8BusinessLabels.labels:type_name -> l8business.L8BusinessLabels.LabelsEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_business_proto_init() }
func file_business_proto_init() {
	if File_business_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_business_proto_rawDesc), len(file_business_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_business_proto_goTypes,
		DependencyIndexes: file_business_proto_depIdxs,
		MessageInfos:      file_business_proto_msgTypes,
	}.Build()
	File_business_proto = out.File
	file_business_proto_goTypes = nil
	file_business_proto_depIdxs = nil
}
