// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: system.proto

package l8system

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type L8SystemAction int32

const (
	L8SystemAction_Invalid_Oper   L8SystemAction = 0
	L8SystemAction_Routes_Add     L8SystemAction = 1
	L8SystemAction_Routes_Remove  L8SystemAction = 2
	L8SystemAction_Service_Add    L8SystemAction = 3
	L8SystemAction_Service_Remove L8SystemAction = 4
)

// Enum value maps for L8SystemAction.
var (
	L8SystemAction_name = map[int32]string{
		0: "Invalid_Oper",
		1: "Routes_Add",
		2: "Routes_Remove",
		3: "Service_Add",
		4: "Service_Remove",
	}
	L8SystemAction_value = map[string]int32{
		"Invalid_Oper":   0,
		"Routes_Add":     1,
		"Routes_Remove":  2,
		"Service_Add":    3,
		"Service_Remove": 4,
	}
)

func (x L8SystemAction) Enum() *L8SystemAction {
	p := new(L8SystemAction)
	*p = x
	return p
}

func (x L8SystemAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L8SystemAction) Descriptor() protoreflect.EnumDescriptor {
	return file_system_proto_enumTypes[0].Descriptor()
}

func (L8SystemAction) Type() protoreflect.EnumType {
	return &file_system_proto_enumTypes[0]
}

func (x L8SystemAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use L8SystemAction.Descriptor instead.
func (L8SystemAction) EnumDescriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{0}
}

type L8SystemMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action  L8SystemAction `protobuf:"varint,1,opt,name=action,proto3,enum=l8system.L8SystemAction" json:"action,omitempty"`
	Publish bool           `protobuf:"varint,2,opt,name=publish,proto3" json:"publish,omitempty"`
	// Types that are assignable to Data:
	//
	//	*L8SystemMessage_RouteTable
	//	*L8SystemMessage_ServiceData
	Data isL8SystemMessage_Data `protobuf_oneof:"data"`
}

func (x *L8SystemMessage) Reset() {
	*x = L8SystemMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8SystemMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8SystemMessage) ProtoMessage() {}

func (x *L8SystemMessage) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8SystemMessage.ProtoReflect.Descriptor instead.
func (*L8SystemMessage) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{0}
}

func (x *L8SystemMessage) GetAction() L8SystemAction {
	if x != nil {
		return x.Action
	}
	return L8SystemAction_Invalid_Oper
}

func (x *L8SystemMessage) GetPublish() bool {
	if x != nil {
		return x.Publish
	}
	return false
}

func (m *L8SystemMessage) GetData() isL8SystemMessage_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *L8SystemMessage) GetRouteTable() *L8RouteTable {
	if x, ok := x.GetData().(*L8SystemMessage_RouteTable); ok {
		return x.RouteTable
	}
	return nil
}

func (x *L8SystemMessage) GetServiceData() *L8ServiceData {
	if x, ok := x.GetData().(*L8SystemMessage_ServiceData); ok {
		return x.ServiceData
	}
	return nil
}

type isL8SystemMessage_Data interface {
	isL8SystemMessage_Data()
}

type L8SystemMessage_RouteTable struct {
	RouteTable *L8RouteTable `protobuf:"bytes,3,opt,name=route_table,json=routeTable,proto3,oneof"`
}

type L8SystemMessage_ServiceData struct {
	ServiceData *L8ServiceData `protobuf:"bytes,4,opt,name=service_data,json=serviceData,proto3,oneof"`
}

func (*L8SystemMessage_RouteTable) isL8SystemMessage_Data() {}

func (*L8SystemMessage_ServiceData) isL8SystemMessage_Data() {}

type L8RouteTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows map[string]string `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *L8RouteTable) Reset() {
	*x = L8RouteTable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8RouteTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8RouteTable) ProtoMessage() {}

func (x *L8RouteTable) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8RouteTable.ProtoReflect.Descriptor instead.
func (*L8RouteTable) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{1}
}

func (x *L8RouteTable) GetRows() map[string]string {
	if x != nil {
		return x.Rows
	}
	return nil
}

type L8ServiceData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceUuid string `protobuf:"bytes,1,opt,name=service_uuid,json=serviceUuid,proto3" json:"service_uuid,omitempty"`
	ServiceName string `protobuf:"bytes,2,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	ServiceArea int32  `protobuf:"varint,3,opt,name=serviceArea,proto3" json:"serviceArea,omitempty"`
}

func (x *L8ServiceData) Reset() {
	*x = L8ServiceData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8ServiceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8ServiceData) ProtoMessage() {}

func (x *L8ServiceData) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8ServiceData.ProtoReflect.Descriptor instead.
func (*L8ServiceData) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{2}
}

func (x *L8ServiceData) GetServiceUuid() string {
	if x != nil {
		return x.ServiceUuid
	}
	return ""
}

func (x *L8ServiceData) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *L8ServiceData) GetServiceArea() int32 {
	if x != nil {
		return x.ServiceArea
	}
	return 0
}

var File_system_proto protoreflect.FileDescriptor

var file_system_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x6c, 0x38, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x22, 0xde, 0x01, 0x0a, 0x0f, 0x4c, 0x38, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x30, 0x0a, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6c,
	0x38, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x4c, 0x38, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x12, 0x39, 0x0a, 0x0b, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x5f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x6c, 0x38, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x4c, 0x38, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x3c, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6c, 0x38, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x2e, 0x4c, 0x38, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x7d, 0x0a, 0x0c, 0x4c, 0x38, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x34, 0x0a, 0x04, 0x72, 0x6f, 0x77,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6c, 0x38, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x2e, 0x4c, 0x38, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x2e,
	0x52, 0x6f, 0x77, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x1a,
	0x37, 0x0a, 0x09, 0x52, 0x6f, 0x77, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x76, 0x0a, 0x0d, 0x4c, 0x38, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x75, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x72, 0x65, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x72, 0x65, 0x61,
	0x2a, 0x6a, 0x0a, 0x0e, 0x4c, 0x38, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x4f, 0x70,
	0x65, 0x72, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x5f, 0x41,
	0x64, 0x64, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x5f, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x41, 0x64, 0x64, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x10, 0x04, 0x42, 0x32, 0x0a, 0x12,
	0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x6c, 0x38, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x42, 0x08, 0x4c, 0x38, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x50, 0x01, 0x5a, 0x10,
	0x2e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x6c, 0x38, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_system_proto_rawDescOnce sync.Once
	file_system_proto_rawDescData = file_system_proto_rawDesc
)

func file_system_proto_rawDescGZIP() []byte {
	file_system_proto_rawDescOnce.Do(func() {
		file_system_proto_rawDescData = protoimpl.X.CompressGZIP(file_system_proto_rawDescData)
	})
	return file_system_proto_rawDescData
}

var file_system_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_system_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_system_proto_goTypes = []interface{}{
	(L8SystemAction)(0),     // 0: l8system.L8SystemAction
	(*L8SystemMessage)(nil), // 1: l8system.L8SystemMessage
	(*L8RouteTable)(nil),    // 2: l8system.L8RouteTable
	(*L8ServiceData)(nil),   // 3: l8system.L8ServiceData
	nil,                     // 4: l8system.L8RouteTable.RowsEntry
}
var file_system_proto_depIdxs = []int32{
	0, // 0: l8system.L8SystemMessage.action:type_name -> l8system.L8SystemAction
	2, // 1: l8system.L8SystemMessage.route_table:type_name -> l8system.L8RouteTable
	3, // 2: l8system.L8SystemMessage.service_data:type_name -> l8system.L8ServiceData
	4, // 3: l8system.L8RouteTable.rows:type_name -> l8system.L8RouteTable.RowsEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_system_proto_init() }
func file_system_proto_init() {
	if File_system_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_system_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8SystemMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8RouteTable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8ServiceData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_system_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*L8SystemMessage_RouteTable)(nil),
		(*L8SystemMessage_ServiceData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_system_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_system_proto_goTypes,
		DependencyIndexes: file_system_proto_depIdxs,
		EnumInfos:         file_system_proto_enumTypes,
		MessageInfos:      file_system_proto_msgTypes,
	}.Build()
	File_system_proto = out.File
	file_system_proto_rawDesc = nil
	file_system_proto_goTypes = nil
	file_system_proto_depIdxs = nil
}
