// © 2025 Sharon Aicler (saichler@gmail.com)
//
// Layer 8 Ecosystem is licensed under the Apache License, Version 2.0.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// system.proto defines internal system messages for cluster management.
// Used for route table updates and service registration/deregistration
// across the Layer 8 distributed network.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: system.proto

package l8system

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// L8SystemAction enumerates the types of system-level operations.
type L8SystemAction int32

const (
	// Invalid or unspecified operation
	L8SystemAction_Invalid_Oper L8SystemAction = 0
	// Add new routes to the routing table
	L8SystemAction_Routes_Add L8SystemAction = 1
	// Remove routes from the routing table
	L8SystemAction_Routes_Remove L8SystemAction = 2
	// Register a new service in the cluster
	L8SystemAction_Service_Add L8SystemAction = 3
	// Deregister a service from the cluster
	L8SystemAction_Service_Remove L8SystemAction = 4
)

// Enum value maps for L8SystemAction.
var (
	L8SystemAction_name = map[int32]string{
		0: "Invalid_Oper",
		1: "Routes_Add",
		2: "Routes_Remove",
		3: "Service_Add",
		4: "Service_Remove",
	}
	L8SystemAction_value = map[string]int32{
		"Invalid_Oper":   0,
		"Routes_Add":     1,
		"Routes_Remove":  2,
		"Service_Add":    3,
		"Service_Remove": 4,
	}
)

func (x L8SystemAction) Enum() *L8SystemAction {
	p := new(L8SystemAction)
	*p = x
	return p
}

func (x L8SystemAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L8SystemAction) Descriptor() protoreflect.EnumDescriptor {
	return file_system_proto_enumTypes[0].Descriptor()
}

func (L8SystemAction) Type() protoreflect.EnumType {
	return &file_system_proto_enumTypes[0]
}

func (x L8SystemAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use L8SystemAction.Descriptor instead.
func (L8SystemAction) EnumDescriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{0}
}

// L8SystemMessage is the envelope for system-level control messages.
// Used for cluster topology changes and service discovery updates.
type L8SystemMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of system action being performed
	Action L8SystemAction `protobuf:"varint,1,opt,name=action,proto3,enum=l8system.L8SystemAction" json:"action,omitempty"`
	// If true, broadcast this message to all nodes; otherwise process locally
	Publish bool `protobuf:"varint,2,opt,name=publish,proto3" json:"publish,omitempty"`
	// The payload, which depends on the action type
	//
	// Types that are valid to be assigned to Data:
	//
	//	*L8SystemMessage_RouteTable
	//	*L8SystemMessage_ServiceData
	Data          isL8SystemMessage_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8SystemMessage) Reset() {
	*x = L8SystemMessage{}
	mi := &file_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8SystemMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8SystemMessage) ProtoMessage() {}

func (x *L8SystemMessage) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8SystemMessage.ProtoReflect.Descriptor instead.
func (*L8SystemMessage) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{0}
}

func (x *L8SystemMessage) GetAction() L8SystemAction {
	if x != nil {
		return x.Action
	}
	return L8SystemAction_Invalid_Oper
}

func (x *L8SystemMessage) GetPublish() bool {
	if x != nil {
		return x.Publish
	}
	return false
}

func (x *L8SystemMessage) GetData() isL8SystemMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *L8SystemMessage) GetRouteTable() *L8RouteTable {
	if x != nil {
		if x, ok := x.Data.(*L8SystemMessage_RouteTable); ok {
			return x.RouteTable
		}
	}
	return nil
}

func (x *L8SystemMessage) GetServiceData() *L8ServiceData {
	if x != nil {
		if x, ok := x.Data.(*L8SystemMessage_ServiceData); ok {
			return x.ServiceData
		}
	}
	return nil
}

type isL8SystemMessage_Data interface {
	isL8SystemMessage_Data()
}

type L8SystemMessage_RouteTable struct {
	// Route table data for Routes_Add/Routes_Remove actions
	RouteTable *L8RouteTable `protobuf:"bytes,3,opt,name=route_table,json=routeTable,proto3,oneof"`
}

type L8SystemMessage_ServiceData struct {
	// Service data for Service_Add/Service_Remove actions
	ServiceData *L8ServiceData `protobuf:"bytes,4,opt,name=service_data,json=serviceData,proto3,oneof"`
}

func (*L8SystemMessage_RouteTable) isL8SystemMessage_Data() {}

func (*L8SystemMessage_ServiceData) isL8SystemMessage_Data() {}

// L8RouteTable contains routing information for message delivery.
// Maps destination identifiers to next-hop addresses.
type L8RouteTable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of destination UUID to next-hop UUID/address
	Rows          map[string]string `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8RouteTable) Reset() {
	*x = L8RouteTable{}
	mi := &file_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8RouteTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8RouteTable) ProtoMessage() {}

func (x *L8RouteTable) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8RouteTable.ProtoReflect.Descriptor instead.
func (*L8RouteTable) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{1}
}

func (x *L8RouteTable) GetRows() map[string]string {
	if x != nil {
		return x.Rows
	}
	return nil
}

// L8ServiceData contains information about a service instance.
// Used for service registration and discovery.
type L8ServiceData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID of the node hosting this service
	ServiceUuid string `protobuf:"bytes,1,opt,name=service_uuid,json=serviceUuid,proto3" json:"service_uuid,omitempty"`
	// Name of the service
	ServiceName string `protobuf:"bytes,2,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	// Area/partition of the service
	ServiceArea   int32 `protobuf:"varint,3,opt,name=serviceArea,proto3" json:"serviceArea,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8ServiceData) Reset() {
	*x = L8ServiceData{}
	mi := &file_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8ServiceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8ServiceData) ProtoMessage() {}

func (x *L8ServiceData) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8ServiceData.ProtoReflect.Descriptor instead.
func (*L8ServiceData) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{2}
}

func (x *L8ServiceData) GetServiceUuid() string {
	if x != nil {
		return x.ServiceUuid
	}
	return ""
}

func (x *L8ServiceData) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *L8ServiceData) GetServiceArea() int32 {
	if x != nil {
		return x.ServiceArea
	}
	return 0
}

var File_system_proto protoreflect.FileDescriptor

const file_system_proto_rawDesc = "" +
	"\n" +
	"\fsystem.proto\x12\bl8system\"\xde\x01\n" +
	"\x0fL8SystemMessage\x120\n" +
	"\x06action\x18\x01 \x01(\x0e2\x18.l8system.L8SystemActionR\x06action\x12\x18\n" +
	"\apublish\x18\x02 \x01(\bR\apublish\x129\n" +
	"\vroute_table\x18\x03 \x01(\v2\x16.l8system.L8RouteTableH\x00R\n" +
	"routeTable\x12<\n" +
	"\fservice_data\x18\x04 \x01(\v2\x17.l8system.L8ServiceDataH\x00R\vserviceDataB\x06\n" +
	"\x04data\"}\n" +
	"\fL8RouteTable\x124\n" +
	"\x04rows\x18\x01 \x03(\v2 .l8system.L8RouteTable.RowsEntryR\x04rows\x1a7\n" +
	"\tRowsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"v\n" +
	"\rL8ServiceData\x12!\n" +
	"\fservice_uuid\x18\x01 \x01(\tR\vserviceUuid\x12 \n" +
	"\vserviceName\x18\x02 \x01(\tR\vserviceName\x12 \n" +
	"\vserviceArea\x18\x03 \x01(\x05R\vserviceArea*j\n" +
	"\x0eL8SystemAction\x12\x10\n" +
	"\fInvalid_Oper\x10\x00\x12\x0e\n" +
	"\n" +
	"Routes_Add\x10\x01\x12\x11\n" +
	"\rRoutes_Remove\x10\x02\x12\x0f\n" +
	"\vService_Add\x10\x03\x12\x12\n" +
	"\x0eService_Remove\x10\x04B2\n" +
	"\x12com.types.l8systemB\bL8SystemP\x01Z\x10./types/l8systemb\x06proto3"

var (
	file_system_proto_rawDescOnce sync.Once
	file_system_proto_rawDescData []byte
)

func file_system_proto_rawDescGZIP() []byte {
	file_system_proto_rawDescOnce.Do(func() {
		file_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_proto_rawDesc), len(file_system_proto_rawDesc)))
	})
	return file_system_proto_rawDescData
}

var file_system_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_system_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_system_proto_goTypes = []any{
	(L8SystemAction)(0),     // 0: l8system.L8SystemAction
	(*L8SystemMessage)(nil), // 1: l8system.L8SystemMessage
	(*L8RouteTable)(nil),    // 2: l8system.L8RouteTable
	(*L8ServiceData)(nil),   // 3: l8system.L8ServiceData
	nil,                     // 4: l8system.L8RouteTable.RowsEntry
}
var file_system_proto_depIdxs = []int32{
	0, // 0: l8system.L8SystemMessage.action:type_name -> l8system.L8SystemAction
	2, // 1: l8system.L8SystemMessage.route_table:type_name -> l8system.L8RouteTable
	3, // 2: l8system.L8SystemMessage.service_data:type_name -> l8system.L8ServiceData
	4, // 3: l8system.L8RouteTable.rows:type_name -> l8system.L8RouteTable.RowsEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_system_proto_init() }
func file_system_proto_init() {
	if File_system_proto != nil {
		return
	}
	file_system_proto_msgTypes[0].OneofWrappers = []any{
		(*L8SystemMessage_RouteTable)(nil),
		(*L8SystemMessage_ServiceData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_proto_rawDesc), len(file_system_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_system_proto_goTypes,
		DependencyIndexes: file_system_proto_depIdxs,
		EnumInfos:         file_system_proto_enumTypes,
		MessageInfos:      file_system_proto_msgTypes,
	}.Build()
	File_system_proto = out.File
	file_system_proto_goTypes = nil
	file_system_proto_depIdxs = nil
}
