// © 2025 Sharon Aicler (saichler@gmail.com)
//
// Layer 8 Ecosystem is licensed under the Apache License, Version 2.0.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// sysconfig.proto defines system configuration types for the Layer 8 network.
// Contains settings for message queues, network connections, and VNet configuration.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: sysconfig.proto

package l8sysconfig

import (
	l8services "github.com/saichler/l8types/go/types/l8services"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// L8SysConfig contains system-wide configuration for message handling and network setup.
// Used to configure VNic (Virtual Network Interface) connections and message limits.
type L8SysConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum data size for a message
	MaxDataSize uint64 `protobuf:"varint,1,opt,name=max_data_size,json=maxDataSize,proto3" json:"max_data_size,omitempty"`
	// The transmit message queue size
	TxQueueSize uint64 `protobuf:"varint,2,opt,name=tx_queue_size,json=txQueueSize,proto3" json:"tx_queue_size,omitempty"`
	// The received message queue size
	RxQueueSize uint64 `protobuf:"varint,3,opt,name=rx_queue_size,json=rxQueueSize,proto3" json:"rx_queue_size,omitempty"`
	// What is the switch port for this configuration
	VnetPort uint32 `protobuf:"varint,4,opt,name=vnet_port,json=vnetPort,proto3" json:"vnet_port,omitempty"`
	// The local uuid
	LocalUuid string `protobuf:"bytes,5,opt,name=local_uuid,json=localUuid,proto3" json:"local_uuid,omitempty"`
	// The remote uuid
	RemoteUuid string `protobuf:"bytes,6,opt,name=remote_uuid,json=remoteUuid,proto3" json:"remote_uuid,omitempty"`
	// The address of the connection initiator, regardless of the side.
	Address string `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	// force external mode in case two switches are on the same machine
	// woth different ports
	ForceExternal bool `protobuf:"varint,8,opt,name=force_external,json=forceExternal,proto3" json:"force_external,omitempty"`
	// Custom local alias for this vnic
	LocalAlias string `protobuf:"bytes,9,opt,name=local_alias,json=localAlias,proto3" json:"local_alias,omitempty"`
	// Custom remote alias for this vnic
	RemoteAlias string `protobuf:"bytes,10,opt,name=remote_alias,json=remoteAlias,proto3" json:"remote_alias,omitempty"`
	// Provided services
	Services *l8services.L8Services `protobuf:"bytes,11,opt,name=services,proto3" json:"services,omitempty"`
	// Keep Alive interval in Seconds
	KeepAliveIntervalSeconds int64 `protobuf:"varint,12,opt,name=keep_alive_interval_seconds,json=keepAliveIntervalSeconds,proto3" json:"keep_alive_interval_seconds,omitempty"`
	// is this a remote vnic
	RemoteVnet string `protobuf:"bytes,13,opt,name=remote_vnet,json=remoteVnet,proto3" json:"remote_vnet,omitempty"`
	// is this a vnic for a vnet
	IAmVnet bool `protobuf:"varint,14,opt,name=i_am_vnet,json=iAmVnet,proto3" json:"i_am_vnet,omitempty"`
	// Logs Config
	LogConfig *L8LogConfig `protobuf:"bytes,15,opt,name=log_config,json=logConfig,proto3" json:"log_config,omitempty"`
	// Data Store Config
	DataStoreConfig *L8DataStoreConfig `protobuf:"bytes,16,opt,name=data_store_config,json=dataStoreConfig,proto3" json:"data_store_config,omitempty"`
	// Time Series Datastore config
	TimeSeriesStoreConfig *L8DataStoreConfig `protobuf:"bytes,17,opt,name=time_series_store_config,json=timeSeriesStoreConfig,proto3" json:"time_series_store_config,omitempty"`
	// Web application endpoint
	WebConfig *L8WebAppConfig `protobuf:"bytes,18,opt,name=web_config,json=webConfig,proto3" json:"web_config,omitempty"`
	// Mounted Directory
	DataDirectory string `protobuf:"bytes,19,opt,name=data_directory,json=dataDirectory,proto3" json:"data_directory,omitempty"`
	// DNS hostname for peer discovery (e.g., a K8s headless Service name)
	DiscoveryDnsName string `protobuf:"bytes,20,opt,name=discovery_dns_name,json=discoveryDnsName,proto3" json:"discovery_dns_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *L8SysConfig) Reset() {
	*x = L8SysConfig{}
	mi := &file_sysconfig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8SysConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8SysConfig) ProtoMessage() {}

func (x *L8SysConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sysconfig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8SysConfig.ProtoReflect.Descriptor instead.
func (*L8SysConfig) Descriptor() ([]byte, []int) {
	return file_sysconfig_proto_rawDescGZIP(), []int{0}
}

func (x *L8SysConfig) GetMaxDataSize() uint64 {
	if x != nil {
		return x.MaxDataSize
	}
	return 0
}

func (x *L8SysConfig) GetTxQueueSize() uint64 {
	if x != nil {
		return x.TxQueueSize
	}
	return 0
}

func (x *L8SysConfig) GetRxQueueSize() uint64 {
	if x != nil {
		return x.RxQueueSize
	}
	return 0
}

func (x *L8SysConfig) GetVnetPort() uint32 {
	if x != nil {
		return x.VnetPort
	}
	return 0
}

func (x *L8SysConfig) GetLocalUuid() string {
	if x != nil {
		return x.LocalUuid
	}
	return ""
}

func (x *L8SysConfig) GetRemoteUuid() string {
	if x != nil {
		return x.RemoteUuid
	}
	return ""
}

func (x *L8SysConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *L8SysConfig) GetForceExternal() bool {
	if x != nil {
		return x.ForceExternal
	}
	return false
}

func (x *L8SysConfig) GetLocalAlias() string {
	if x != nil {
		return x.LocalAlias
	}
	return ""
}

func (x *L8SysConfig) GetRemoteAlias() string {
	if x != nil {
		return x.RemoteAlias
	}
	return ""
}

func (x *L8SysConfig) GetServices() *l8services.L8Services {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *L8SysConfig) GetKeepAliveIntervalSeconds() int64 {
	if x != nil {
		return x.KeepAliveIntervalSeconds
	}
	return 0
}

func (x *L8SysConfig) GetRemoteVnet() string {
	if x != nil {
		return x.RemoteVnet
	}
	return ""
}

func (x *L8SysConfig) GetIAmVnet() bool {
	if x != nil {
		return x.IAmVnet
	}
	return false
}

func (x *L8SysConfig) GetLogConfig() *L8LogConfig {
	if x != nil {
		return x.LogConfig
	}
	return nil
}

func (x *L8SysConfig) GetDataStoreConfig() *L8DataStoreConfig {
	if x != nil {
		return x.DataStoreConfig
	}
	return nil
}

func (x *L8SysConfig) GetTimeSeriesStoreConfig() *L8DataStoreConfig {
	if x != nil {
		return x.TimeSeriesStoreConfig
	}
	return nil
}

func (x *L8SysConfig) GetWebConfig() *L8WebAppConfig {
	if x != nil {
		return x.WebConfig
	}
	return nil
}

func (x *L8SysConfig) GetDataDirectory() string {
	if x != nil {
		return x.DataDirectory
	}
	return ""
}

func (x *L8SysConfig) GetDiscoveryDnsName() string {
	if x != nil {
		return x.DiscoveryDnsName
	}
	return ""
}

type L8LogConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogDirectory  string                 `protobuf:"bytes,1,opt,name=log_directory,json=logDirectory,proto3" json:"log_directory,omitempty"`
	VnetPort      uint32                 `protobuf:"varint,2,opt,name=vnet_port,json=vnetPort,proto3" json:"vnet_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8LogConfig) Reset() {
	*x = L8LogConfig{}
	mi := &file_sysconfig_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8LogConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8LogConfig) ProtoMessage() {}

func (x *L8LogConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sysconfig_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8LogConfig.ProtoReflect.Descriptor instead.
func (*L8LogConfig) Descriptor() ([]byte, []int) {
	return file_sysconfig_proto_rawDescGZIP(), []int{1}
}

func (x *L8LogConfig) GetLogDirectory() string {
	if x != nil {
		return x.LogDirectory
	}
	return ""
}

func (x *L8LogConfig) GetVnetPort() uint32 {
	if x != nil {
		return x.VnetPort
	}
	return 0
}

type L8DataStoreConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Port          string                 `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8DataStoreConfig) Reset() {
	*x = L8DataStoreConfig{}
	mi := &file_sysconfig_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8DataStoreConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8DataStoreConfig) ProtoMessage() {}

func (x *L8DataStoreConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sysconfig_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8DataStoreConfig.ProtoReflect.Descriptor instead.
func (*L8DataStoreConfig) Descriptor() ([]byte, []int) {
	return file_sysconfig_proto_rawDescGZIP(), []int{2}
}

func (x *L8DataStoreConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *L8DataStoreConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *L8DataStoreConfig) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type L8WebAppConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WebPort        uint32                 `protobuf:"varint,1,opt,name=web_port,json=webPort,proto3" json:"web_port,omitempty"`
	EndPointPrefix string                 `protobuf:"bytes,2,opt,name=end_point_prefix,json=endPointPrefix,proto3" json:"end_point_prefix,omitempty"`
	DomainCertPem  string                 `protobuf:"bytes,3,opt,name=domain_cert_pem,json=domainCertPem,proto3" json:"domain_cert_pem,omitempty"`
	PrivateKeyPem  string                 `protobuf:"bytes,4,opt,name=private_key_pem,json=privateKeyPem,proto3" json:"private_key_pem,omitempty"`
	PublicKeyPem   string                 `protobuf:"bytes,5,opt,name=public_key_pem,json=publicKeyPem,proto3" json:"public_key_pem,omitempty"`
	CertLoadDir    string                 `protobuf:"bytes,6,opt,name=cert_load_dir,json=certLoadDir,proto3" json:"cert_load_dir,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *L8WebAppConfig) Reset() {
	*x = L8WebAppConfig{}
	mi := &file_sysconfig_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8WebAppConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8WebAppConfig) ProtoMessage() {}

func (x *L8WebAppConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sysconfig_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8WebAppConfig.ProtoReflect.Descriptor instead.
func (*L8WebAppConfig) Descriptor() ([]byte, []int) {
	return file_sysconfig_proto_rawDescGZIP(), []int{3}
}

func (x *L8WebAppConfig) GetWebPort() uint32 {
	if x != nil {
		return x.WebPort
	}
	return 0
}

func (x *L8WebAppConfig) GetEndPointPrefix() string {
	if x != nil {
		return x.EndPointPrefix
	}
	return ""
}

func (x *L8WebAppConfig) GetDomainCertPem() string {
	if x != nil {
		return x.DomainCertPem
	}
	return ""
}

func (x *L8WebAppConfig) GetPrivateKeyPem() string {
	if x != nil {
		return x.PrivateKeyPem
	}
	return ""
}

func (x *L8WebAppConfig) GetPublicKeyPem() string {
	if x != nil {
		return x.PublicKeyPem
	}
	return ""
}

func (x *L8WebAppConfig) GetCertLoadDir() string {
	if x != nil {
		return x.CertLoadDir
	}
	return ""
}

var File_sysconfig_proto protoreflect.FileDescriptor

const file_sysconfig_proto_rawDesc = "" +
	"\n" +
	"\x0fsysconfig.proto\x12\vl8sysconfig\x1a\x0eservices.proto\"\xfa\x06\n" +
	"\vL8SysConfig\x12\"\n" +
	"\rmax_data_size\x18\x01 \x01(\x04R\vmaxDataSize\x12\"\n" +
	"\rtx_queue_size\x18\x02 \x01(\x04R\vtxQueueSize\x12\"\n" +
	"\rrx_queue_size\x18\x03 \x01(\x04R\vrxQueueSize\x12\x1b\n" +
	"\tvnet_port\x18\x04 \x01(\rR\bvnetPort\x12\x1d\n" +
	"\n" +
	"local_uuid\x18\x05 \x01(\tR\tlocalUuid\x12\x1f\n" +
	"\vremote_uuid\x18\x06 \x01(\tR\n" +
	"remoteUuid\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12%\n" +
	"\x0eforce_external\x18\b \x01(\bR\rforceExternal\x12\x1f\n" +
	"\vlocal_alias\x18\t \x01(\tR\n" +
	"localAlias\x12!\n" +
	"\fremote_alias\x18\n" +
	" \x01(\tR\vremoteAlias\x122\n" +
	"\bservices\x18\v \x01(\v2\x16.l8services.L8ServicesR\bservices\x12=\n" +
	"\x1bkeep_alive_interval_seconds\x18\f \x01(\x03R\x18keepAliveIntervalSeconds\x12\x1f\n" +
	"\vremote_vnet\x18\r \x01(\tR\n" +
	"remoteVnet\x12\x1a\n" +
	"\ti_am_vnet\x18\x0e \x01(\bR\aiAmVnet\x127\n" +
	"\n" +
	"log_config\x18\x0f \x01(\v2\x18.l8sysconfig.L8LogConfigR\tlogConfig\x12J\n" +
	"\x11data_store_config\x18\x10 \x01(\v2\x1e.l8sysconfig.L8DataStoreConfigR\x0fdataStoreConfig\x12W\n" +
	"\x18time_series_store_config\x18\x11 \x01(\v2\x1e.l8sysconfig.L8DataStoreConfigR\x15timeSeriesStoreConfig\x12:\n" +
	"\n" +
	"web_config\x18\x12 \x01(\v2\x1b.l8sysconfig.L8WebAppConfigR\twebConfig\x12%\n" +
	"\x0edata_directory\x18\x13 \x01(\tR\rdataDirectory\x12,\n" +
	"\x12discovery_dns_name\x18\x14 \x01(\tR\x10discoveryDnsName\"O\n" +
	"\vL8LogConfig\x12#\n" +
	"\rlog_directory\x18\x01 \x01(\tR\flogDirectory\x12\x1b\n" +
	"\tvnet_port\x18\x02 \x01(\rR\bvnetPort\"O\n" +
	"\x11L8DataStoreConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\"\xef\x01\n" +
	"\x0eL8WebAppConfig\x12\x19\n" +
	"\bweb_port\x18\x01 \x01(\rR\awebPort\x12(\n" +
	"\x10end_point_prefix\x18\x02 \x01(\tR\x0eendPointPrefix\x12&\n" +
	"\x0fdomain_cert_pem\x18\x03 \x01(\tR\rdomainCertPem\x12&\n" +
	"\x0fprivate_key_pem\x18\x04 \x01(\tR\rprivateKeyPem\x12$\n" +
	"\x0epublic_key_pem\x18\x05 \x01(\tR\fpublicKeyPem\x12\"\n" +
	"\rcert_load_dir\x18\x06 \x01(\tR\vcertLoadDirB;\n" +
	"\x15com.types.l8sysconfigB\vL8SysconfigP\x01Z\x13./types/l8sysconfigb\x06proto3"

var (
	file_sysconfig_proto_rawDescOnce sync.Once
	file_sysconfig_proto_rawDescData []byte
)

func file_sysconfig_proto_rawDescGZIP() []byte {
	file_sysconfig_proto_rawDescOnce.Do(func() {
		file_sysconfig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sysconfig_proto_rawDesc), len(file_sysconfig_proto_rawDesc)))
	})
	return file_sysconfig_proto_rawDescData
}

var file_sysconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sysconfig_proto_goTypes = []any{
	(*L8SysConfig)(nil),           // 0: l8sysconfig.L8SysConfig
	(*L8LogConfig)(nil),           // 1: l8sysconfig.L8LogConfig
	(*L8DataStoreConfig)(nil),     // 2: l8sysconfig.L8DataStoreConfig
	(*L8WebAppConfig)(nil),        // 3: l8sysconfig.L8WebAppConfig
	(*l8services.L8Services)(nil), // 4: l8services.L8Services
}
var file_sysconfig_proto_depIdxs = []int32{
	4, // 0: l8sysconfig.L8SysConfig.services:type_name -> l8services.L8Services
	1, // 1: l8sysconfig.L8SysConfig.log_config:type_name -> l8sysconfig.L8LogConfig
	2, // 2: l8sysconfig.L8SysConfig.data_store_config:type_name -> l8sysconfig.L8DataStoreConfig
	2, // 3: l8sysconfig.L8SysConfig.time_series_store_config:type_name -> l8sysconfig.L8DataStoreConfig
	3, // 4: l8sysconfig.L8SysConfig.web_config:type_name -> l8sysconfig.L8WebAppConfig
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sysconfig_proto_init() }
func file_sysconfig_proto_init() {
	if File_sysconfig_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sysconfig_proto_rawDesc), len(file_sysconfig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sysconfig_proto_goTypes,
		DependencyIndexes: file_sysconfig_proto_depIdxs,
		MessageInfos:      file_sysconfig_proto_msgTypes,
	}.Build()
	File_sysconfig_proto = out.File
	file_sysconfig_proto_goTypes = nil
	file_sysconfig_proto_depIdxs = nil
}
