// © 2025 Sharon Aicler (saichler@gmail.com)
//
// Layer 8 Ecosystem is licensed under the Apache License, Version 2.0.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// services.proto defines types for service discovery, replication, and transactions
// in the Layer 8 distributed system. Services are organized into areas for scalability
// and can be replicated across multiple nodes for high availability.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: services.proto

package l8services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// L8Services maps service names to their available service areas.
// Used for service discovery and routing decisions.
type L8Services struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of service name to the areas where that service is available
	ServiceToAreas map[string]*L8ServiceAreas `protobuf:"bytes,1,rep,name=service_to_areas,json=serviceToAreas,proto3" json:"service_to_areas,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *L8Services) Reset() {
	*x = L8Services{}
	mi := &file_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8Services) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8Services) ProtoMessage() {}

func (x *L8Services) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8Services.ProtoReflect.Descriptor instead.
func (*L8Services) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{0}
}

func (x *L8Services) GetServiceToAreas() map[string]*L8ServiceAreas {
	if x != nil {
		return x.ServiceToAreas
	}
	return nil
}

// L8ServiceAreas represents a set of service area IDs.
// Areas are used to partition services for scalability and locality.
type L8ServiceAreas struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of area ID to availability flag (true = available)
	Areas         map[int32]bool   `protobuf:"bytes,1,rep,name=areas,proto3" json:"areas,omitempty" protobuf_key:"zigzag32,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Models        map[int32]string `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty" protobuf_key:"zigzag32,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8ServiceAreas) Reset() {
	*x = L8ServiceAreas{}
	mi := &file_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8ServiceAreas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8ServiceAreas) ProtoMessage() {}

func (x *L8ServiceAreas) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8ServiceAreas.ProtoReflect.Descriptor instead.
func (*L8ServiceAreas) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{1}
}

func (x *L8ServiceAreas) GetAreas() map[int32]bool {
	if x != nil {
		return x.Areas
	}
	return nil
}

func (x *L8ServiceAreas) GetModels() map[int32]string {
	if x != nil {
		return x.Models
	}
	return nil
}

// L8ReplicationIndex tracks replication state for a service area.
// Maintains information about which data keys are stored where.
type L8ReplicationIndex struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the service being replicated
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Service area this index belongs to
	ServiceArea int32 `protobuf:"zigzag32,2,opt,name=service_area,json=serviceArea,proto3" json:"service_area,omitempty"`
	// Map of data key to its replication information
	Keys map[string]*L8ReplicationKey `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Map of keys that have been extracted/processed
	Extracted     map[string]bool `protobuf:"bytes,4,rep,name=extracted,proto3" json:"extracted,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8ReplicationIndex) Reset() {
	*x = L8ReplicationIndex{}
	mi := &file_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8ReplicationIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8ReplicationIndex) ProtoMessage() {}

func (x *L8ReplicationIndex) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8ReplicationIndex.ProtoReflect.Descriptor instead.
func (*L8ReplicationIndex) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{2}
}

func (x *L8ReplicationIndex) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *L8ReplicationIndex) GetServiceArea() int32 {
	if x != nil {
		return x.ServiceArea
	}
	return 0
}

func (x *L8ReplicationIndex) GetKeys() map[string]*L8ReplicationKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *L8ReplicationIndex) GetExtracted() map[string]bool {
	if x != nil {
		return x.Extracted
	}
	return nil
}

// L8ReplicationKey contains replication location information for a single key.
type L8ReplicationKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of replica ID to location index
	Location map[string]int32 `protobuf:"bytes,1,rep,name=location,proto3" json:"location,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// The primary replica ID (replica 0)
	Replica0      string `protobuf:"bytes,2,opt,name=replica0,proto3" json:"replica0,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8ReplicationKey) Reset() {
	*x = L8ReplicationKey{}
	mi := &file_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8ReplicationKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8ReplicationKey) ProtoMessage() {}

func (x *L8ReplicationKey) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8ReplicationKey.ProtoReflect.Descriptor instead.
func (*L8ReplicationKey) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{3}
}

func (x *L8ReplicationKey) GetLocation() map[string]int32 {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *L8ReplicationKey) GetReplica0() string {
	if x != nil {
		return x.Replica0
	}
	return ""
}

// L8Transaction represents a distributed transaction and its lifecycle.
// Tracks the transaction through various states from creation to completion.
type L8Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current transaction state (see TransactionState enum in interfaces)
	State int32 `protobuf:"varint,1,opt,name=State,proto3" json:"State,omitempty"`
	// Unique transaction identifier
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Error message if transaction failed
	ErrMsg string `protobuf:"bytes,3,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	// Timestamp when transaction was created (Unix millis)
	Created int64 `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	// Timestamp when transaction was queued for execution
	Queued int64 `protobuf:"varint,5,opt,name=queued,proto3" json:"queued,omitempty"`
	// Timestamp when transaction started running
	Running int64 `protobuf:"varint,6,opt,name=running,proto3" json:"running,omitempty"`
	// Timestamp when transaction completed
	End           int64 `protobuf:"varint,7,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8Transaction) Reset() {
	*x = L8Transaction{}
	mi := &file_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8Transaction) ProtoMessage() {}

func (x *L8Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8Transaction.ProtoReflect.Descriptor instead.
func (*L8Transaction) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{4}
}

func (x *L8Transaction) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *L8Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *L8Transaction) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *L8Transaction) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *L8Transaction) GetQueued() int64 {
	if x != nil {
		return x.Queued
	}
	return 0
}

func (x *L8Transaction) GetRunning() int64 {
	if x != nil {
		return x.Running
	}
	return 0
}

func (x *L8Transaction) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

var File_services_proto protoreflect.FileDescriptor

const file_services_proto_rawDesc = "" +
	"\n" +
	"\x0eservices.proto\x12\n" +
	"l8services\"\xc1\x01\n" +
	"\n" +
	"L8Services\x12T\n" +
	"\x10service_to_areas\x18\x01 \x03(\v2*.l8services.L8Services.ServiceToAreasEntryR\x0eserviceToAreas\x1a]\n" +
	"\x13ServiceToAreasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.l8services.L8ServiceAreasR\x05value:\x028\x01\"\x82\x02\n" +
	"\x0eL8ServiceAreas\x12;\n" +
	"\x05areas\x18\x01 \x03(\v2%.l8services.L8ServiceAreas.AreasEntryR\x05areas\x12>\n" +
	"\x06models\x18\x02 \x03(\v2&.l8services.L8ServiceAreas.ModelsEntryR\x06models\x1a8\n" +
	"\n" +
	"AreasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x11R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a9\n" +
	"\vModelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x11R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfa\x02\n" +
	"\x12L8ReplicationIndex\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12!\n" +
	"\fservice_area\x18\x02 \x01(\x11R\vserviceArea\x12<\n" +
	"\x04keys\x18\x03 \x03(\v2(.l8services.L8ReplicationIndex.KeysEntryR\x04keys\x12K\n" +
	"\textracted\x18\x04 \x03(\v2-.l8services.L8ReplicationIndex.ExtractedEntryR\textracted\x1aU\n" +
	"\tKeysEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.l8services.L8ReplicationKeyR\x05value:\x028\x01\x1a<\n" +
	"\x0eExtractedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\xb3\x01\n" +
	"\x10L8ReplicationKey\x12F\n" +
	"\blocation\x18\x01 \x03(\v2*.l8services.L8ReplicationKey.LocationEntryR\blocation\x12\x1a\n" +
	"\breplica0\x18\x02 \x01(\tR\breplica0\x1a;\n" +
	"\rLocationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xac\x01\n" +
	"\rL8Transaction\x12\x14\n" +
	"\x05State\x18\x01 \x01(\x05R\x05State\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x17\n" +
	"\aerr_msg\x18\x03 \x01(\tR\x06errMsg\x12\x18\n" +
	"\acreated\x18\x04 \x01(\x03R\acreated\x12\x16\n" +
	"\x06queued\x18\x05 \x01(\x03R\x06queued\x12\x18\n" +
	"\arunning\x18\x06 \x01(\x03R\arunning\x12\x10\n" +
	"\x03end\x18\a \x01(\x03R\x03endB7\n" +
	"\x13com.types.l8serviceB\n" +
	"L8ServicesP\x01Z\x12./types/l8servicesb\x06proto3"

var (
	file_services_proto_rawDescOnce sync.Once
	file_services_proto_rawDescData []byte
)

func file_services_proto_rawDescGZIP() []byte {
	file_services_proto_rawDescOnce.Do(func() {
		file_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_proto_rawDesc), len(file_services_proto_rawDesc)))
	})
	return file_services_proto_rawDescData
}

var file_services_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_services_proto_goTypes = []any{
	(*L8Services)(nil),         // 0: l8services.L8Services
	(*L8ServiceAreas)(nil),     // 1: l8services.L8ServiceAreas
	(*L8ReplicationIndex)(nil), // 2: l8services.L8ReplicationIndex
	(*L8ReplicationKey)(nil),   // 3: l8services.L8ReplicationKey
	(*L8Transaction)(nil),      // 4: l8services.L8Transaction
	nil,                        // 5: l8services.L8Services.ServiceToAreasEntry
	nil,                        // 6: l8services.L8ServiceAreas.AreasEntry
	nil,                        // 7: l8services.L8ServiceAreas.ModelsEntry
	nil,                        // 8: l8services.L8ReplicationIndex.KeysEntry
	nil,                        // 9: l8services.L8ReplicationIndex.ExtractedEntry
	nil,                        // 10: l8services.L8ReplicationKey.LocationEntry
}
var file_services_proto_depIdxs = []int32{
	5,  // 0: l8services.L8Services.service_to_areas:type_name -> l8services.L8Services.ServiceToAreasEntry
	6,  // 1: l8services.L8ServiceAreas.areas:type_name -> l8services.L8ServiceAreas.AreasEntry
	7,  // 2: l8services.L8ServiceAreas.models:type_name -> l8services.L8ServiceAreas.ModelsEntry
	8,  // 3: l8services.L8ReplicationIndex.keys:type_name -> l8services.L8ReplicationIndex.KeysEntry
	9,  // 4: l8services.L8ReplicationIndex.extracted:type_name -> l8services.L8ReplicationIndex.ExtractedEntry
	10, // 5: l8services.L8ReplicationKey.location:type_name -> l8services.L8ReplicationKey.LocationEntry
	1,  // 6: l8services.L8Services.ServiceToAreasEntry.value:type_name -> l8services.L8ServiceAreas
	3,  // 7: l8services.L8ReplicationIndex.KeysEntry.value:type_name -> l8services.L8ReplicationKey
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_services_proto_init() }
func file_services_proto_init() {
	if File_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_proto_rawDesc), len(file_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_proto_goTypes,
		DependencyIndexes: file_services_proto_depIdxs,
		MessageInfos:      file_services_proto_msgTypes,
	}.Build()
	File_services_proto = out.File
	file_services_proto_goTypes = nil
	file_services_proto_depIdxs = nil
}
