// © 2025 Sharon Aicler (saichler@gmail.com)
//
// Layer 8 Ecosystem is licensed under the Apache License, Version 2.0.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// web.proto defines types for HTTP/REST web service integration.
// Enables Layer 8 services to expose HTTP endpoints with configurable
// request/response mappings and plugin support.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: web.proto

package l8web

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// L8WebService defines a web service configuration for exposing HTTP endpoints.
// Maps HTTP methods to service handlers and manages plugin data.
type L8WebService struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the backing Layer 8 service
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Service area to route requests to
	ServiceArea int32 `protobuf:"varint,2,opt,name=service_area,json=serviceArea,proto3" json:"service_area,omitempty"`
	// Map of HTTP method (ordinal) to endpoint configuration
	Endpoints map[int32]*L8WebServiceEndpoint `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Plugin configuration for custom processing
	Plugin *L8Plugin `protobuf:"bytes,4,opt,name=plugin,proto3" json:"plugin,omitempty"`
	// Virtual network identifier for routing
	Vnet          uint32 `protobuf:"varint,5,opt,name=vnet,proto3" json:"vnet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8WebService) Reset() {
	*x = L8WebService{}
	mi := &file_web_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8WebService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8WebService) ProtoMessage() {}

func (x *L8WebService) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8WebService.ProtoReflect.Descriptor instead.
func (*L8WebService) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{0}
}

func (x *L8WebService) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *L8WebService) GetServiceArea() int32 {
	if x != nil {
		return x.ServiceArea
	}
	return 0
}

func (x *L8WebService) GetEndpoints() map[int32]*L8WebServiceEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *L8WebService) GetPlugin() *L8Plugin {
	if x != nil {
		return x.Plugin
	}
	return nil
}

func (x *L8WebService) GetVnet() uint32 {
	if x != nil {
		return x.Vnet
	}
	return 0
}

// L8WebServiceEndpoint configures the request/response mapping for an HTTP endpoint.
type L8WebServiceEndpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of request body type to response type (fully qualified type names)
	Body2Response map[string]string `protobuf:"bytes,1,rep,name=body2Response,proto3" json:"body2Response,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Default/primary request body type when not explicitly specified
	PrimaryBody   string `protobuf:"bytes,2,opt,name=primaryBody,proto3" json:"primaryBody,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8WebServiceEndpoint) Reset() {
	*x = L8WebServiceEndpoint{}
	mi := &file_web_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8WebServiceEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8WebServiceEndpoint) ProtoMessage() {}

func (x *L8WebServiceEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8WebServiceEndpoint.ProtoReflect.Descriptor instead.
func (*L8WebServiceEndpoint) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{1}
}

func (x *L8WebServiceEndpoint) GetBody2Response() map[string]string {
	if x != nil {
		return x.Body2Response
	}
	return nil
}

func (x *L8WebServiceEndpoint) GetPrimaryBody() string {
	if x != nil {
		return x.PrimaryBody
	}
	return ""
}

// L8Plugin contains arbitrary plugin configuration data.
// Used by web service plugins for custom behavior.
type L8Plugin struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plugin-specific configuration data (typically JSON or other serialized format)
	Data          string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8Plugin) Reset() {
	*x = L8Plugin{}
	mi := &file_web_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8Plugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8Plugin) ProtoMessage() {}

func (x *L8Plugin) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8Plugin.ProtoReflect.Descriptor instead.
func (*L8Plugin) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{2}
}

func (x *L8Plugin) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// L8Empty is an empty message used as a placeholder for void requests/responses.
type L8Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L8Empty) Reset() {
	*x = L8Empty{}
	mi := &file_web_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L8Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8Empty) ProtoMessage() {}

func (x *L8Empty) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8Empty.ProtoReflect.Descriptor instead.
func (*L8Empty) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{3}
}

var File_web_proto protoreflect.FileDescriptor

const file_web_proto_rawDesc = "" +
	"\n" +
	"\tweb.proto\x12\x05l8web\"\xae\x02\n" +
	"\fL8WebService\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12!\n" +
	"\fservice_area\x18\x02 \x01(\x05R\vserviceArea\x12@\n" +
	"\tendpoints\x18\x03 \x03(\v2\".l8web.L8WebService.EndpointsEntryR\tendpoints\x12'\n" +
	"\x06plugin\x18\x04 \x01(\v2\x0f.l8web.L8PluginR\x06plugin\x12\x12\n" +
	"\x04vnet\x18\x05 \x01(\rR\x04vnet\x1aY\n" +
	"\x0eEndpointsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.l8web.L8WebServiceEndpointR\x05value:\x028\x01\"\xd0\x01\n" +
	"\x14L8WebServiceEndpoint\x12T\n" +
	"\rbody2Response\x18\x01 \x03(\v2..l8web.L8WebServiceEndpoint.Body2ResponseEntryR\rbody2Response\x12 \n" +
	"\vprimaryBody\x18\x02 \x01(\tR\vprimaryBody\x1a@\n" +
	"\x12Body2ResponseEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1e\n" +
	"\bL8Plugin\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"\t\n" +
	"\aL8EmptyB)\n" +
	"\x0fcom.types.l8webB\x05L8WebP\x01Z\r./types/l8webb\x06proto3"

var (
	file_web_proto_rawDescOnce sync.Once
	file_web_proto_rawDescData []byte
)

func file_web_proto_rawDescGZIP() []byte {
	file_web_proto_rawDescOnce.Do(func() {
		file_web_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_web_proto_rawDesc), len(file_web_proto_rawDesc)))
	})
	return file_web_proto_rawDescData
}

var file_web_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_web_proto_goTypes = []any{
	(*L8WebService)(nil),         // 0: l8web.L8WebService
	(*L8WebServiceEndpoint)(nil), // 1: l8web.L8WebServiceEndpoint
	(*L8Plugin)(nil),             // 2: l8web.L8Plugin
	(*L8Empty)(nil),              // 3: l8web.L8Empty
	nil,                          // 4: l8web.L8WebService.EndpointsEntry
	nil,                          // 5: l8web.L8WebServiceEndpoint.Body2ResponseEntry
}
var file_web_proto_depIdxs = []int32{
	4, // 0: l8web.L8WebService.endpoints:type_name -> l8web.L8WebService.EndpointsEntry
	2, // 1: l8web.L8WebService.plugin:type_name -> l8web.L8Plugin
	5, // 2: l8web.L8WebServiceEndpoint.body2Response:type_name -> l8web.L8WebServiceEndpoint.Body2ResponseEntry
	1, // 3: l8web.L8WebService.EndpointsEntry.value:type_name -> l8web.L8WebServiceEndpoint
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_web_proto_init() }
func file_web_proto_init() {
	if File_web_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_proto_rawDesc), len(file_web_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_web_proto_goTypes,
		DependencyIndexes: file_web_proto_depIdxs,
		MessageInfos:      file_web_proto_msgTypes,
	}.Build()
	File_web_proto = out.File
	file_web_proto_goTypes = nil
	file_web_proto_depIdxs = nil
}
